### ISSUE TITLE
Storing PHP sessions in Azure Table Storage

### ISSUE THREAD

**Issue by nowenL** [Azure/azure-storage-php#10]
Migrate from Azure/azure-sdk-for-php#680

In this Windows Azure SDK for PHP, it looks like doesn't implemented a Session Handler for PHP. I was found that there is do exist in the CodePlex project, but it just said "Deprecated in favor of the new SDK on GitHub".

So are you going to implement a new version of PHP Session Handler in this new Windows Azure SDK for PHP?

**Comment by ScottHelme** [comment]
I wrote a session library for CodeIgniter but you should be able to easily adapt it if you just need session handling code: https://scotthelme.co.uk/offloading-php-session-storage-to-azure-table-storage/

**Comment by nowenL** [comment]
Thanks Scott! Amazing article.

I notice it's based on the old storage SDK. Any plan to migrate it to the new one?

**Comment by ScottHelme** [comment]
I've just pushed some changes now :-)

**Comment by nowenL** [comment]
Awesome! :) 

Any specific reason to use WindowsAzure\Common\ServicesBuilder instead of the new one?

**Comment by ScottHelme** [comment]
That wasn't mentioned in the release notes: https://github.com/Azure/azure-sdk-for-php/releases/tag/v0.4.3 

Should it also be changed?

**Comment by nowenL** [comment]
Yes. Should be changed as well if it's used for creating storage service. I see you already opened an issue in azure-sdk-for-php about ServiceException Azure/azure-sdk-for-php#841. I'll add my voice there. :)

**Comment by ScottHelme** [comment]
Ah ok, I will update the references in my test environments tonight and see how it goes. With the latest update I saw quite a large performance boost, any ideas on why and was it to be expected?

**Comment by nowenL** [comment]
You mean after updating from the old storage SDK to this one? I guess it might be caused by the change of underlying http client library. We replaced HttpRequest2 with Guzzle in the new SDK.

**Comment by ScottHelme** [comment]
I didn't update to this one, I just went up to the latest azure-sdk-for-php (0.4.3). This SDK is still marked as pre-release so I'm a little hesitant.

**Comment by nowenL** [comment]
Azure-sdk-for-php has removed the storage service API and referenced to this SDK since v0.4.3, so actually you are using this SDK if you depends on azure-sdk-for-php v0.4.3. :)
