### ISSUE TITLE
wrong XMLSerializer in ServiceException.php

### ISSUE THREAD

**Issue by yogesh2490** [Azure/azure-storage-php#100]
ServiceException class uses wrong XMLSerializer. There is no such file exists it suppose to be MicrosoftAzure\Storage\Common\Internal\Serialization\ **XmlSerializer**. 
I tried to create pull request for fix but i guess i don't have permission.

**Comment by XiaoningLiu** [comment]
Hi @yogesh2490 

Thanks for reporting! Don't worry, I'll fix that!

**Comment by XiaoningLiu** [comment]
BTW, is there any restrictions when you tried to make a pull request?

**Comment by yogesh2490** [comment]
Thanks for changing it. I think i was doing something wrong for pull request.
