### ISSUE TITLE
Namespaced tests broken on case-sensitive filesystems

### ISSUE THREAD

**Issue by z38** [Azure/azure-storage-php#102]
When trying to run the unit tests, PHPUnit is unable to find all classes on a case-sensitive filesystem:
```text
PHP Fatal error:  Class 'MicrosoftAzure\Storage\Tests\Framework\ServiceRestProxyTestBase' not found in /app/azure-storage-php/tests/framework/BlobServiceRestProxyTestBase.php on line 43
```

IMHO, the cleanest approach would be to convert the first letter of all subfolders in `tests/` to uppercase. I'm happy to submit a pull-request, however the request should get merged relatively quickly to avoid merge conflicts.

As an alternative, the autoloader can be adjusted to avoid moving all test files.

**Comment by XiaoningLiu** [comment]
Hi @z38

Thanks for reporting that! PR is welcome. We are just starting the validation work of next release. We can release with the changes if your PR is created before Sep. 20th (Wednesday). Or we have to put it into our next release : )
