### ISSUE TITLE
Is there wiki page for all the function names that we can use for different classes.

### ISSUE THREAD

**Issue by yogesh2490** [Azure/azure-storage-php#106]
I might be missing something but is there any wiki page which shows all the function names and its input value details. This is example i was more talking about So i was trying to get the blob from container and store in specific file name. [This url](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-php-how-to-use-blobs) gave me example how to download the blob but after looking into BlobSamples i was able to get the correct function. So i was wondering if we come up with some wiki page which have all the function name and its use on one page then it would be useful to search things. This is just [example](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_restful_http_httprequest.htm#apex_classes_restful_http_httprequest). Not necessary that detail but something like that on wiki page. I am ready to contribute.

**Comment by XiaoningLiu** [comment]
Hi @yogesh2490 

Azure Storage PHP Client Library has a GitHub page hosting API references.
- https://azure.github.io/azure-storage-php

By the way, is there any error on the https://docs.microsoft.com/en-us/azure/storage/blobs/storage-php-how-to-use-blobs#download-a-blob ?

**Comment by yogesh2490** [comment]
There is no error i was more looking for saveBlobToFile function. Thanks for sharing API reference.
