### ISSUE TITLE
EdmType::INT32 is ignored when adding a string property value

### ISSUE THREAD

**Issue by spaze** [Azure/azure-storage-php#114]
When creating a new property value like this

```
$entity->addProperty('test', EdmType::INT32, 'a');
```

the `EdmType::INT32` type is ignored and the property is created as String.  I think it should be created as Int32.

The reason for that is that `EdmType::serializeValue()` returns exactly the same variable, intact, when `EdmType::INT32` is used, and `EdmType::typeRequired($edmType)` returns false for Int32 too, so the type is not serialized to the JSON sent to Table Storage.

The similar probably happens when
```
$entity->addProperty('test', EdmType::STRING, 123);
```
the result would be Int32 property.

Proposed fix: in `EdmType::serializeValue()`, the value should be type-casted according to the type specified, something like

```
        switch ($type) {
        case EdmType::INT32:
            return intval($value);
        case EdmType::INT64:
        case EdmType::GUID:
        case EdmType::STRING:
            return strval($value);
        case null:
            return $value;
```

I'll make a PR later, would appreciate any input if the proposed would be a correct behavior.

Thanks!

**Comment by XiaoningLiu** [comment]
Thanks!
