### ISSUE TITLE
CopyBlobFrom URL Include Issue

### ISSUE THREAD

**Issue by boredom2** [Azure/azure-storage-php#116]
Hi there,

a small Problem is: using copyBlobFromURL() without an explicit CopyBlobFromURLOptions(), the Code crashes due to include/reference Issues. It could easily be fixed by chaning Line 3845 of BlobRestProxy - the created Instance should be from the Namespace Models - then it works without any Problems.

Thanks!

**Comment by katmsft** [comment]
Duly noted, thanks for reporting the issue. @XiaoningLiu You might want to look  into this.

**Comment by XiaoningLiu** [comment]
Sure, will fix, thanks for reporting!

**Comment by XiaoningLiu** [comment]
Hi, this issue is resolved in GA release v1.0.0. Please refer to package https://packagist.org/packages/microsoft/azure-storage-blob
