### ISSUE TITLE
TableRestProxy does not return Results

### ISSUE THREAD

**Issue by boredom2** [Azure/azure-storage-php#128]
We face the Situation, that a Query on Table Storage does not return any Results.
The same Query in other Tools (like Azure Storage Explorer) does return Results though - and mostly, the SDK returns Items also.
Due to the Fact, that this is hard to find out, I guess, its a probably a TimeOut Issue. (it does not occur permanently, only sometimes) - and there is indeed thousands of Write and Read Operations on the specific Accounts per Minute.
After investigating some Commits, I found out, that there is a second Parameter to createTableService, which takes an Argument for Guzzle (I suppose). I couldnt find any documented Example, but is this correct:

`...::createTableService($this->connection,['http'=>['timeout'=>15]]);`

If this is correct (and sets the Guzzle Timeout to 15 Seconds) then the Reason is not a Timeout (because it still does not return any Results). Otherwise, could someone hint me to the correct Usage of this Parameter?

Thanks!
Christoph

**Comment by katmsft** [comment]
Hi, Thanks for raising the problem.
It is most likely that the server actually returned a continuation token, with which user has to call the API again for remaining result. Sometimes the initial list operation will return no items but only a continuation token. Please see [Query Timeout and Pagination for Azure Storage](https://docs.microsoft.com/en-us/rest/api/storageservices/query-timeout-and-pagination) for more details.

If you want to write your own code to enumerate the results, I would suggest that you reference the blob sample [here](https://github.com/Azure/azure-storage-php/blob/dev/samples/BlobSamples.php#L430) which is our suggested practice for this case.

If that solves your problem, please change the issue title to 'List operation does not return any results except for a continuation token' and we will leave this issue open as this issue has been raised many times across many languages' Azure Storage Client Libraries. In this way it will be easier for customers who encountered the same problem to be aware of the solution.

We have also discussed whether we should provide convenience API that would enumerate the continuation token for our users. But we have also seen a lot of our users reporting resource consumption issues when they have a huge amount of items when it comes to list operations, and it is hard for them to debug in the first place not knowing the API is actually doing a lot of REST calls in the background and each of them is very resource consuming. Therefore our current decision is not to provide such API, at least in PHP, Ruby, Node and Python.

**Comment by katmsft** [comment]
As for the timeout issue, there is currently a built in `$timeout` in `MicrosoftAzure\Storage\Common\Models\ServiceOptions`, and it would work for most of the Blob, Queue and File operations. However for table, it does not work since server does not provide such functionality. Please see [here](https://docs.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-table-service-operations) for more information.

**Comment by boredom2** [comment]
Thanks.
There is indeed a Case, where I got no Results, but Continuation Tokens.
Fixed, thanks.,
