### ISSUE TITLE
batchInsertEntitiesSample Example throws error

### ISSUE THREAD

**Issue by Karrtojal** [Azure/azure-storage-php#129]
Testing the Table samples, in the batchInsertEntitiesSample method:
```
function batchInsertEntitiesSample($tableClient, $mytable)
{
    $batchOp = new BatchOperations();
    for ($i = 2; $i < 10; ++$i) {
        $entity = new Entity();
        $entity->setPartitionKey("pk");
        $entity->setRowKey(''.$i);
        $entity->addProperty("PropertyName", EdmType::STRING, "Sample".$i);
        $entity->addProperty("Description", null, "Sample description.");
        $batchOp->addInsertEntity($mytable, $entity);
    }
    
    try {
        $tableClient->batch($batchOp);
    } catch (ServiceException $e) {
        $code = $e->getCode();
        $error_message = $e->getMessage();
        echo $code.": ".$error_message.PHP_EOL;
    }
}
```

The output is always something like this:
400: Fail: Code: 400 Value: Bad Request details (if any): {"odata.error":{"code":"BadRequest","message":{"lang":"en-us","value":"One of the input values is invalid.\r\nActivityId: 0b0f6445-d44c-4d82-aff5-742982f30ddc, documentdb-dotnet-sdk/1.20.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0\nRequestID:0b0f6445-d44c-4d82-aff5-742982f30ddc\n"}}} . 

The entity is a simple string. I can't see what is missing.
Thanks in advance.

**Comment by XiaoningLiu** [comment]
@Karrtojal 

The sample runs well on my side. Do you use a valid Azure Storage account? This SDK is for Azure Storage Table.

**Comment by Karrtojal** [comment]
Yes, I use a valid Azure Storage account. The insertEntitySample method works perfectly, with the same $entity variable.
I've used the  https://github.com/Azure/azure-storage-php/ project, with composer....

**Comment by XiaoningLiu** [comment]
Do you mean ```batchInsertEntitiesSample``` doesn't work but ```insertEntitySample``` work? It's strange. I found keyword **documentdb-dotnet-sdk** in your error message, do you use documentDB?

**Comment by Karrtojal** [comment]
Yes, that's correct. insertEntitySample works very well. It's very strange.
The cosmbodb API was Azure Tables.
![imagen](https://user-images.githubusercontent.com/37321813/37414243-f7b34e10-27a8-11e8-9046-7e4b6dd3653d.png)

**Comment by XiaoningLiu** [comment]
@Karrtojal I got it. You are using this library for CosmosDB with Table API. Actually, this library is not officially validated with CosmosDB Table API (Although most of the methods should work). It only validated with Azure Storage Table. https://azure.microsoft.com/en-us/services/storage/tables/

Now CosmosDB Table API has .Net, Node.js, Java & Python SDKs support. See https://docs.microsoft.com/en-us/azure/cosmos-db/create-table-dotnet

We are trying to do the supporting in following months.

**Comment by Karrtojal** [comment]
Ok, thanks XiaoningLiu for your investigation.

**Comment by deepakyadav** [comment]
This issue has been fixed by the CosmosDB team on the server side. Thanks for reporting it.
