### ISSUE TITLE
Receive 403 Failure trying to create a file due to file type (mp3)

### ISSUE THREAD

**Issue by jondmcelroy** [Azure/azure-storage-php#130]
When attempting to upload a mp3 file to the file share using createFileFromContent, I received a 403 with this error message:

> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

Code to reproduce is simple:

```
$share = "test-share";
$sourcePath = "C:\file.mp3";
$path = "files\file.mp3";
$file = fopen($sourcePath, "r");
$fileClient->createFileFromContent($share, $path, $file);
```

The problem appears to occur when the putFileRangeAsync call is made inside the createFileFromContent. When sending a Put Range, content type is not sent, which matches the docs here: https://docs.microsoft.com/en-us/rest/api/storageservices/put-range.

The response from the server though is indicating that the server wants the content type.
```
The MAC signature found in the HTTP request 'xxxxx' is not the same as any computed signature. Server used following string to sign:
PUT


454032

audio/mpeg
Thu, 15 Mar 2018 17:37:35 GMT





x-ms-range:bytes=0-454031
x-ms-request-id:5aaaaf5f5c9f5
x-ms-version:2016-05-31
x-ms-write:Update
/test-storage/test-share/files/file.mp3
```

The SDK is signing with this string:
```
PUT


454032


Thu, 15 Mar 2018 17:37:35 GMT





x-ms-range:bytes=0-454031
x-ms-request-id:5aaaaf5f5c9f5
x-ms-version:2016-05-31
x-ms-write:Update
/test-storage/test-share/files/file.mp3
```
The only difference is that the server is for some reason wanting the content type of 'audio/mpeg'.

If I change the file to not have a mp3 filename and change this code to this:
```
$share = "test-share";
$sourcePath = "C:\file";
$path = "files\file.mp3";
$file = fopen($sourcePath, "r");
$fileClient->createFileFromContent($share, $path, $file);
```
Then it works fine.

Is this a problem with the SDK not sending the content type or an issue with the server expecting something that should not be sent?

**Comment by XiaoningLiu** [comment]
Hi @jondmcelroy I can re-produce this issue on my side. There are 2 HTTP requests for ```createFileFromContents```, first is to create a file and then upload data with PUT request. The issue is in the second step.

This SDK doesn't set header "content-type" and  generate auth token without this header in second step. However, when under-layer HTTP library ```Guzzle``` send out this request, the header was set. 

I tried to debug into ```Guzzle```'s code, but no good. As far as I know, there is a work around for it. Use ```stream_get_contents``` to convert resource into a stream. If you want to add it's content-type header, please use use option ```CreateFileOptions::$contentType```.

```
$fileClient->createFileFromContent($shareName, $fileName, stream_get_contents(fopen('123.mp3', 'r')));
```
