### ISSUE TITLE
PHP Fatal Error: fopen(): Failed to enable crypto

### ISSUE THREAD

**Issue by srguglielmo** [Azure/azure-storage-php#133]
Hello,

I have a Windows Web App service running PHP 7.2. The Web App has PHP code that reads data from Azure Blob Storage. My code to do this is based on the examples given in this repo.

Everything seems to be working properly during our testing. However, once we start adding web traffic load to the Web App (by running an Azure Performance Test or other external load), the PHP error logs start filling up with  the below error. IIS throws a Internal Server Error as well.

This is confusing because it works perfectly fine during testing. One thought I had was because the errors below point to openssl, it may be a lack of randomness available to generate https connections to the Azure Blob Service. However, this is  just a speculation on my part.

Thank you!

```
   [02-Apr-2018 10:45:35 America/New_York] PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
   error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed 
   [file] D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
   [line] 324
   [message] fopen(): Failed to enable crypto
   [file] D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
   [line] 324
   [message] fopen(https://XXXX.blob.core.windows.net/YYYY/ZZZZ): failed to open stream: operation failed
   [file] D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
   [line] 324 in D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php:252
   Stack trace:
   #0 D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(335): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
   #1 D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(52): GuzzleHtt in D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 52
```

**Comment by srguglielmo** [comment]
Here is the code we're using (with account keys/etc removed)

```
<?php
	$AccountName = 'REMOVED';
	$AccountKey = 'REMOVED';
	$Container = 'REMOVED';
	$Key = 'REMOVED'

	require_once('vendor/autoload.php');
	use MicrosoftAzure\Storage\Blob\BlobRestProxy;
	use MicrosoftAzure\Storage\Common\ServiceException;
	$BlobClient = BlobRestProxy::createBlobService('DefaultEndpointsProtocol=https;AccountName=' . $AccountName . ';AccountKey=' . $AccountKey);

	try {
		$Blob = $BlobClient->getBlob($Container, $Key);
	} catch (ServiceException $e) {
		error_log("Fatal Error: Failed to get key $Key from Azure Blob Storage\nError Code: " . $e->getCode() . "\nMessage: " . $e->getMessage() . "\n");
		exit(1);
	}
	$Contents = stream_get_contents($Blob->getContentStream());
	$LiteStatus = json_decode($Contents, TRUE);
	if ($LiteStatus == "REMOVED") {
		// Do stuff here
	} else {
		// Do other stuff here
	}
?>
```

**Comment by XiaoningLiu** [comment]
Hi @srguglielmo , your code should be ok. According to your description, the error only happens when workload is heavy, is that right?

I'm afraid that Storage Client Library cannot do something to solve this, because the errors are deep in Guzzle and below.

I found similar issues on the StackOverflow. Disabling the SSL validation seems as a workaround, but it's a potential risk in production. 

https://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-and-more

$options['http'] will pass to Guzzle as options. 'verify' can be customized according to Guzzle's documentation. There are some suggestions from Guzzle about how to customize and debug with CA issues.

```
$options['http'] = ['verify' => false]; // Disable validation entirely
$options['http'] = ['verify' => true];  // Use the system's CA bundle (this is the default setting) 
$options['http'] = ['verify' => "/TestFiles/cacert.pem"]; // Use a custom SSL certificate on disk.

$blobClient = BlobRestProxy::createBlobService(
    $connectionString,
    $options
);
```

http://docs.guzzlephp.org/en/stable/request-options.html#verify

```
Not all system's have a known CA bundle on disk. For example, Windows and OS X do not have a single common location for CA bundles. When setting "verify" to true, Guzzle will do its best to find the most appropriate CA bundle on your system. When using cURL or the PHP stream wrapper on PHP versions >= 5.6, this happens by default. When using the PHP stream wrapper on versions < 5.6, Guzzle tries to find your CA bundle in the following order:

Check if openssl.cafile is set in your php.ini file.
Check if curl.cainfo is set in your php.ini file.
Check if /etc/pki/tls/certs/ca-bundle.crt exists (Red Hat, CentOS, Fedora; provided by the ca-certificates package)
Check if /etc/ssl/certs/ca-certificates.crt exists (Ubuntu, Debian; provided by the ca-certificates package)
Check if /usr/local/share/certs/ca-root-nss.crt exists (FreeBSD; provided by the ca_root_nss package)
Check if /usr/local/etc/openssl/cert.pem (OS X; provided by homebrew)
Check if C:\windows\system32\curl-ca-bundle.crt exists (Windows)
Check if C:\windows\curl-ca-bundle.crt exists (Windows)
The result of this lookup is cached in memory so that subsequent calls in the same process will return very quickly. However, when sending only a single request per-process in something like Apache, you should consider setting the openssl.cafile environment variable to the path on disk to the file so that this entire process is skipped.

If you do not need a specific certificate bundle, then Mozilla provides a commonly used CA bundle which can be downloaded here (provided by the maintainer of cURL). Once you have a CA bundle available on disk, you can set the "openssl.cafile" PHP ini setting to point to the path to the file, allowing you to omit the "verify" request option. Much more detail on SSL certificates can be found on the cURL website.
```

**Comment by srguglielmo** [comment]
Hi @XiaoningLiu,

Thank you for your quick response and  suggestions.

It's correct that this issue only occurs when the server is receiving HTTP traffic. However,  it is not required to have an excessively high load; it occurs with a Azure WebApp Performance Test of *just 10 virtual users*.  I also tested using a 3rd party load test vendor with 50 virtual users. The same error occurred.

As a test, I have followed your suggestion of disabling certificate validation in Guzzle:

```
require_once('vendor/autoload.php');
use MicrosoftAzure\Storage\Blob\BlobRestProxy;
use MicrosoftAzure\Storage\Common\ServiceException;
$BlobClientOptions['http'] = ['verify' => FALSE]; // Disable certificate validation for testing
$BlobClient = BlobRestProxy::createBlobService(
    'DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY',
    $BlobClientOptions
);

try {
    $Blob = $BlobClient->getBlob('container', 'key');
} catch (ServiceException $e) {
    error_log("FATAL ERROR: Failed to get key 'key' from Azure Blob Storage!\r\nCode: " . $e->getCode() . "\r\nMessage: " . $e->getMessage());
    exit(1);
}

$Contents = stream_get_contents($Blob->getContentStream());
$LiteStatus = json_decode($Contents, TRUE);
if ($LiteStatus = .....) {
	// Do stuff
} else {
	// Do other stuff
}
```

However, this had no change. It worked fine for my own personal testing, however once some load was applied to the website, the PHP errors occurred and the website began throwing 500 Internal Server Errors again.

I have also tried switching the version of PHP on the WebApp Service from 7.2 to 7.1 and also tried 7.0. This had no change either.

Please note that this is for an enterprise Azure subscription and we are also working with our Technical Account Manager on this (however, he is not a PHP expert).

Thank you!
Steve

**Comment by XiaoningLiu** [comment]
Hi @srguglielmo

As a workaround, we can switch the default endpoints protocol from HTTPS to HTTP:
```
$BlobClient = BlobRestProxy::createBlobService('DefaultEndpointsProtocol=http;AccountName=' . $AccountName . ';AccountKey=' . $AccountKey);
```

I'm wondering whether it's related to the crypto/openssl module. It's possible to test within a Azure PHP Web APP on Linux?

Best,
Xiaoning

**Comment by srguglielmo** [comment]
Hi @XiaoningLiu,

This issue seemed to be solved by caching the data from Azure Blob Storage. I believe that when website traffic starts to increase, either PHP's openssl/crypto libraries or something in the Azure libraries becomes overwhelmed and starts throwing this error. I used [WinCache's User Cache](http://php.net/manual/en/intro.wincache.php) API to cache the Azure Blob Storage data for 10 seconds. A quick example of my code:

```
$data = wincache_ucache_get('myKey', $success); // Try to fetch from cache
if (false === $success) {
    // Data not  found in cache; fetch from Azure Blob Storage into $data

    // -- code removed --

    wincache_ucache_set('myKey', $data, 10); // Put data in cache with TTL of 10 seconds
}

echo $data; // Send data to the HTTP client
```

We are still testing this, however so far, this caching in PHP for 10 seconds seemed to alleviate the load and solved this issue.

Thank you!
Steve

**Comment by XiaoningLiu** [comment]
Thanks again for sharing your solution. It will be very valuable for other users who may face with the same issue.

It's very interesting that it's a traffic related issue. Azure Storage library is a thin HTTP request wrapper. There should be some under layer issues beyond our control.

**Comment by OJezu** [comment]
Why is this closed? Caching data is not a solution. Even if the issue is caused by a library, why was not this taken upstream?

**Comment by XiaoningLiu** [comment]
@OJezu Did you have a same issue?

I found an almost same issue in https://github.com/guzzle/guzzle/issues/1752, but treated as not a Guzzle issue.

**Comment by OJezu** [comment]
We had same container image working in some deployments and fail in others with this error, with same Azure API endpoint. I don't know for sure what was the factor differentiating the two cases. We had everything working in a staging deployment and failing 100% in a production deployment. The production deployment is receiving more traffic, but not a terrific amount, less than 100 requests/minute, and most of those don't cause calls to azure-storage-php.

**Comment by OJezu** [comment]
PHP run-time etc. are all part of the container image, we are running in an AKS cluster. Only difference between the environments are loaded application configuration - using different storage containers (oin same account, same endpoint, same key), and higher load.

The loaded configuration is not even remotely touching ca list, it's our configuration used only by our PHP app.

We have switched to HTTP endpoint for now, as it's all in an azure vnet anyway (at least should be), but for sake of security requirements we should switch back to HTTPS when possible.

**Comment by XiaoningLiu** [comment]
Sure. You can also enable storage account firewall to only accept the cluster requests for security.

**Comment by MarcelDevG** [comment]
I'm having what looks like same issues. Calling a dotnet core api from a php site gives the same errors on the php site as mentioned above.

**Comment by XiaoningLiu** [comment]
@MarcelDevG what do you mean calling a dotnet core api from php?

**Comment by MarcelDevG** [comment]
Just as in the issue above, calling the an api (build with dotnet core), under some load, raise the same errors as described here with calling the storage api. W've also switched to http.
So, it looks like the problem is on the side of the caller, but the php is running on a app service which gives little control of the stack.

**Comment by XiaoningLiu** [comment]
@MarcelDevG Thanks for your sharing. So your scenario is building a PHP application which calling into HTTP(s) APIs created by dotnet core? Without dependency to storage SDK, the same issue still happens?

I'm not sure the issue is related to app service or not. But app service seems the common factor shared by srguglielmo and you.
