### ISSUE TITLE
Uncertain how to use Continuation Tokens for Markers

### ISSUE THREAD

**Issue by shairozan** [Azure/azure-storage-php#135]
So I have a blob storage container with hundreds of thousands of blobs in it. I need to get a listing of all the blobs in order to get their total bytes  in length. I'm currently trying to iterate through the blobs, get their properties and length in bytes. 

My problem is that it always caps at 5000. The maxresults component of the API is apparently only used for limiting the results, so that doesn't do me any good. I can see that I get a continuation token on the list blobs operation, but I can't see anywhere that mentions how to actually use that token. 

The setmarker method on the ListBlobsResult class is protected, so I can't set it from outside of the class itself. 

How do I get the full set of blobs using the ContinuationMarkerToken?

**Comment by XiaoningLiu** [comment]
Hi @shairozan , see samples provided in the sample folder.

https://github.com/Azure/azure-storage-php/blob/d4488ca78096fa3af3b8c97bf4ed8074d9d773ae/samples/BlobSamples.php#L434

```
        $listBlobsOptions = new ListBlobsOptions();
        // Setting max result to some value.
        $listBlobsOptions->setMaxResults(100);
        do {
            $blob_list = $blobClient->listBlobs($myContainer, $listBlobsOptions);
            foreach ($blob_list->getBlobs() as $blob) {
                echo $blob->getName().": ".$blob->getUrl().PHP_EOL;
            }
            $listBlobsOptions->setContinuationToken($blob_list->getContinuationToken());
        } while ($blob_list->getContinuationToken());
```
