### ISSUE TITLE
Support for update CORS setting?

### ISSUE THREAD

**Issue by Walk4Muscle** [Azure/azure-storage-php#14]
It seems even the new Azure Storage SDK still doesn't support the CORS settings for blobs or containers as to set the `origin` header shown at https://msdn.microsoft.com/en-us/library/azure/dd179451.aspx.
Will it be supported in some day?

**Comment by nowenL** [comment]
Yes, CORS support is planned in our following releases. However, we don't have accurate release date to share yet.

**Comment by activatedgeek** [comment]
@nowenL In fact, I believe all the options need to be covered as per [https://msdn.microsoft.com/en-us/library/azure/hh452235.aspx](https://msdn.microsoft.com/en-us/library/azure/hh452235.aspx)

**Comment by activatedgeek** [comment]
Just migrated my code base to this repository that it won't be as bad as the previous SDK.

**Comment by nowenL** [comment]
Correct. We are going to support all service setting in REST version 2015-04-05.

Regarding the codes, given you can specify up to 5 CORS rules(AllowedOrigins, AllowedMethods...) under CORS, you should not put them directly under CORS . Besides all looks good to me.

**Comment by katmsft** [comment]
@Walk4Muscle @activatedgeek 
Update CORS settings is now available in release 0.14.0, check it out!
