### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable. 

### ISSUE THREAD

**Issue by Robjam** [Azure/azure-storage-php#141]
Moved from old [repository](https://github.com/Azure/azure-sdk-for-php/issues/979)

Environment:
PHP 7.2
WordPress 4.6.5

Error:
count(): Parameter must be an array or an object that implements Countable.
at line 67 of HttpGuzzle/handler/CurlFactory.php

This [issue](https://github.com/guzzle/guzzle/issues/1973) was resolved in HttpGuzzle in 6.3.

It also appears the [google sdk](https://github.com/google/google-api-php-client/issues/1377) had a similar issue that was resolved.

**Comment by XiaoningLiu** [comment]
Hi @Robjam 

We depends on Guzzle `~6.0`, and will automatically install latest guzzle. 

https://github.com/Azure/azure-storage-php/blob/1afdf1c788a729ed486a6ef1c2e74d3db7b199b9/azure-storage-common/composer.json#L15

**Comment by Robjam** [comment]
Works for me. Thanks for the info!
