### ISSUE TITLE
[Question/Comment] Get the blob Url ?

### ISSUE THREAD

**Issue by epourail** [Azure/azure-storage-php#144]
In order to share/expose a "public" blob, can you set the visibility of the `BlobRestProxy::getBlobUrl()` method to `public` to get the url of a given blob.

Before create a PR, I would appreciate a feedback.

**Comment by katmsft** [comment]
It should be a straight forward fix without any problems, do other services also need this kind of method to be public?

**Comment by epourail** [comment]
PR created
