### ISSUE TITLE
"Call to a member function getStatusCode() on null" on ConnectException with RetryMiddlewareFactory

### ISSUE THREAD

**Issue by spaze** [Azure/azure-storage-php#147]
I'm trying to retry the request on receiving `GuzzleHttp\Exception\ConnectException` (my requests time out sometimes). For that I'm using the `MicrosoftAzure\Storage\Common\Middlewares\RetryMiddleware` like this:

	$this->tableService->pushMiddleware(RetryMiddlewareFactory::create());

I emulate the connection problems by specifying dummy endpoint when creating the storage service (`TableEndpoint=http://127.0.0.1:1002;` - a random IP address and port), `ConnectException` is raised but with RetryMiddleware I get this error:

```
Call to a member function getStatusCode() on null in
.../src/Common/Middlewares/RetryMiddlewareFactory.php:171
```

That's because the retry decider (created by `createRetryDecider()`) ignores `ConnectException` here:
https://github.com/Azure/azure-storage-php/blob/1afdf1c788a729ed486a6ef1c2e74d3db7b199b9/azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php#L160-L167

And assigns `null` to `$response` and then it's trying to call `getStatusCode()` on `null` here:
https://github.com/Azure/azure-storage-php/blob/1afdf1c788a729ed486a6ef1c2e74d3db7b199b9/azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php#L169-L173

I'd like to fix the issue, and there are several options how to do that:
1. Don't retry on `ConnectException`
2. Retry on `ConnectException`
3. Let the developer decide whether they want to when creating the middleware – the retry decider would accept one more parameter: `$retryConnect = false`.

I'd like to see number 3. and can submit a pull request for that (or any other option), please let me know.

Thank you!

**Comment by spaze** [comment]
I've tested the changes for my case so I've already prepared the PR too (with option 3. above), feel free to check that #148 . Thanks!

**Comment by katmsft** [comment]
Thanks for reporting the issue, this is valid scenario. I have reviewed the PR and has some minor comments. Thanks for the contribution.

**Comment by XiaoningLiu** [comment]
@spaze Your PR has been released. Thanks for contribution!

**Comment by spaze** [comment]
Thank you! Closing this one.
