### ISSUE TITLE
Namespace in readme.md is incorrect

### ISSUE THREAD

**Issue by andybeak** [Azure/azure-storage-php#152]
The readme says that you need to `use MicrosoftAzure\Storage\Common\ServiceException;` to process exceptions.  

This namespace is incorrect, it should be `use MicrosoftAzure\Storage\Common\Exceptions\ServiceException;`

**Comment by XiaoningLiu** [comment]
@andybeach @katmsft Will include into incoming release. Thanks for reporting.

**Comment by XiaoningLiu** [comment]
Should close as fix already released.
