### ISSUE TITLE
Unable to finde vendor folder ?

### ISSUE THREAD

**Issue by MunishChechi** [Azure/azure-storage-php#154]
As per first step:
require_once "vendor/autoload.php"; 

Did not find vendor directory in repo.

Please help to setup it.

**Comment by ivodvb** [comment]
Do you have the composer.json file in the current directory?
Does it contain the required packages?
```
microsoft/azure-storage-blob
microsoft/azure-storage-table
microsoft/azure-storage-queue
microsoft/azure-storage-file
```

Did you run `composer install`?

**Comment by katmsft** [comment]
Hi, thanks for reporting the issue. Have you tried @ivodvb 's solution? It should work.

**Comment by MunishChechi** [comment]
Thanks. I installed it with composer and its working now.

**Comment by AryanKumar** [comment]
> 
> 
> Do you have the composer.json file in the current directory?
> Does it contain the required packages?
> 
> ```
> microsoft/azure-storage-blob
> microsoft/azure-storage-table
> microsoft/azure-storage-queue
> microsoft/azure-storage-file
> ```
> 
> Did you run `composer install`?

I run the composer not able to upload the file please can you check my composer.json file  https://prnt.sc/tdocpf
autoload.php:- https://prnt.sc/tdoai6
