### ISSUE TITLE
Allow passing Guzzle client options

### ISSUE THREAD

**Issue by Sazpaimon** [Azure/azure-storage-php#16]
I want to be able to pass options to the Guzzle client (like HTTP timeout). I'm able to do this on the old SDK by setting up a request filter and doing something like `$request->setConfig('timeout', $timeout)`, but this isn't available anymore.

**Comment by nowenL** [comment]
Thanks for your feedback. There's already an item in our backlog to expose more http setting in the interface, including “proxy”, "verify", "timeout" and etc.

**Comment by Sazpaimon** [comment]
Thanks, this is currently a blocker for me to migrate over from the SDK

**Comment by vinjiang** [comment]
@Sazpaimon , thanks for your feedback and we will prioritize our backlog accordingly. BTW, we also welcome community contribution, feel free to send PR(s) if you already have some code prepared. Thanks!

**Comment by Sazpaimon** [comment]
If I were to make a PR, would you be okay with an implementation similar to how the AWS SDK accepts http options? For reference: https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html

The AWS SDK allows setting Guzzle options in the `http` array of the client (which would similar to services here), or as an `@http` parameter to an individual request.  Would this be okay or do you have another implementation in mind?

**Comment by nowenL** [comment]
Actually I was thinking to expose guzzle option similar to what you mentioned: Add an array parameter in ServiceBuilder factory method and pass it to the internal guzzle client constructor. However I didn't plan to expose these setting for individual request, mostly for the simplicity of interface. Is there any specific http settings that blocks you if they can only be set per service?

**Comment by Sazpaimon** [comment]
There's nothing that blocks me now, but I can see options being set on individual requests, such as progress callbacks, being useful.
