### ISSUE TITLE
Best/better syntax for copying blobs

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-storage-php#169]
There doesn't seem to be any comprehensive documentation for this library, so maybe I just haven't found it yet - but if I want to create an operation that performs a copy between two azure storage accounts/containers, what is my best option?

![image](https://user-images.githubusercontent.com/115199/51816739-aaa23100-228d-11e9-827c-3efef3a04864.png)

Judging from this signature, it looks like I can copy between two containers that are in the same storage account, but that syntax doesn't give me any indication as to how I would also perform the copy if the two destinations were different storage accounts.  Moreover, I don't think I like the idea of having to call two different functions for a copy based on having to know whether the source and destinations are on different storage accounts.

Is there any way the operation can be unified so that as an SDK user, I'm only having to call one method?

**Comment by XiaoningLiu** [comment]
Try `copyBlobFromURL`, `$sourceBlob` is a URL pointing to source blob in the original storage account. Usually, the URL has a valid SAS.

http://azure.github.io/azure-storage-php/

![image](https://user-images.githubusercontent.com/6889160/51879630-42e40700-23af-11e9-9b19-502d52bb7e5d.png)

**Comment by katmsft** [comment]
Since the question is addressed this issue will be closed. Thanks for raising the question!
