### ISSUE TITLE
set medadate when creating blockblob doesn't work

### ISSUE THREAD

**Issue by Walk4Muscle** [Azure/azure-storage-php#17]
It seems that there is a mistake at https://github.com/Azure/azure-storage-php/blob/master/src/Blob/Models/CreateBlobOptions.php#L399, which describes the `setMetadata()` function in `MicrosoftAzure\Storage\Blob\Models\CreateBlobOptions` should receive a string param, but in my test, when set string, it will raise a exception similar as `Fatal error: Uncaught MicrosoftAzure\Storage\Common\Internal\InvalidArgumentTypeException: The provided variable 'metadata' should be of type 'array' in E:\Projects\PHP\azure-storage-php\code_sample\vendor\microsoft\azure-storage\src\Common\Internal\Validate.php`.

But if I set an array param in this function, the blob upload to Azure storage successfully, but without any `metadata`. The same issue when I use `CommitBlobBlocksOptions()` model. 

Is it a bug, or is there a mistake when I using the option models?

**Comment by nowenL** [comment]
Thanks for finding this issue. setMetadata() in CreateBlobOptions requires an array instead of a string as parameter. The document is wrong, we will fixed it in our next release.

However, in my test, the metadata is set correctly if an array is used:

    $metadata = array('foo' => 'bar', 'aaa' => 'bbb');
    $options = new CreateBlobOptions();
    $options->setMetadata($metadata);
    $blobRestProxy->createBlockBlob($containerName, 'blobname', 'content', $options);

Can you share more details how you find this problem?

**Comment by Walk4Muscle** [comment]
As I forgot to set `setIncludeMetadata(true)` in `ListBlobsOptions`.
Now is fine. 
Thanks.
