### ISSUE TITLE
How do I create shared access URIs for multipart uploads?

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-storage-php#170]
As a comparison, when I'm working with the AWS SDK, I'm able to initialize a multipart upload and then generate presigned URLs for each chunk.  I'd like to be able to do the same using Azure storage, but it seems difficult to find clear guidance on how to do so with the Azure Storage PHP SDK.

I believe what I'm looking for is some kind of SAS, but then I'm not sure how to set up a multipart (or single part) upload and then send URIs to the client so that it can upload directly to the container.

**Comment by XiaoningLiu** [comment]
@atrauzzi 

### For data transfer

Azure Storage has similar design like AWS S3's multipart uploading.

Generally, S3 needs 3 steps to finish a multipart uploading.
1. Initiate multipart uploading, get a uploadID
2. Upload part with the uploadID and partNumber
3. Complete multipart uploading with selected PartNumbers and Etags

For Azure Storage, there are 2 steps:
1. _Do not need to initialize a multipart uploading_
2. Upload block (like S3's part) to a blockblob with the blockID
3. Commit the blocklist to save the blockblob with the blockIDs

For Azure Storage PHP SDK:
1. `createBlobBlock()` is to upload a block. `commitBlobBlocks()` is to commit blocklist.
2. `createBlockBlob()` has already implemented a concurrency uploading based on above 2 REST APIs.

### For authorization

SAS is another topic about authentication and authorization. You can generate a SAS based on storage account name & key. Every client get the SAS will have the permission granted in the SAS.

**Comment by atrauzzi** [comment]
Sorry @xiaoningliu, you misunderstand.

I want to use pre-authorized URLs to have the client upload directly to the container without my application server having to receive the bytes.

I don't want to grant the client access to do anything more except upload the specific parts of the file.  This is accomplished by having my server send the client presigned upload URIs.

Also, how do I generate the SAS token with the PHP SDK?

**Comment by XiaoningLiu** [comment]
For blockblob, a SAS URL can grant write permission in **blob** level, cannot in **block** (part) level.

With a SAS URL (a URL with SAS query parameter), you can define a URL is granted only with the write permission to a blockblob. Share the SAS URL to the client, so the client can `Create Block`, `Commit Block`.

https://github.com/Azure/azure-storage-php/blob/c6fd3d949e94b634305255d9a29fe70a147fb356/samples/BlobSamples.php#L373

**Comment by atrauzzi** [comment]
`generateBlobDownloadLinkWithSAS` sounds like a download link.  Is there just a plain `generateSAS` then?

**Comment by XiaoningLiu** [comment]
This is a sample to generate SAS for a blob with read permission. You can change permission to `w` to get a SAS with only write permission.

**Comment by XiaoningLiu** [comment]
I'm afraid not. Will discuss this as a potential feature with our team.

**Comment by atrauzzi** [comment]
@XiaoningLiu - Sure thing.

My reason for wanting support for signing individual requests would be exactly the same as when I want to do so with S3, which does support this.  

1. When a client initiates an upload, it splits the file into `n` chunks.
2. It sends a request to my API server, informing that it has `n` chunks of `ceil(fileSize / chunkSize)`.
3. The API server performs an authorization check according to my own domain and then responds with an upload ID and an array of presigned public URIs for my bucket.  Each URI is a `PUT/POST` to the bucket at a specific GUID path.
4. The client receives these URIs and sends one request for each one to the bucket, with the bytes for the upload.
5. After uploading each chunk, the client informs my API that the pieces are ready.  This "completes" the upload, reassembling the pieces at the GUID key path my API originally determined.
6. The binary data is now available for my API to manipulate, such as transferring transfer bucket-to-bucket

The advantage of this approach is that clients aren't granted access to write to any arbitrary key in the bucket.  The only path they can write to is the path that my API server has pre-signed requests for.  In this way, I'm able to allow direct-to-S3 bucket uploads without ever having an authorization active for operations I didn't specifically allow for.

**Comment by XiaoningLiu** [comment]
Thanks @atrauzzi for the detailed explanation. Currently the most similar approach in Azure Storage is, you can generate a SAS URL with write permission for a single blob in the API server. Then send the SAS URL to a client, the client then only have permission to upload to that blob.

**Comment by atrauzzi** [comment]
Right, but that doesn't accomplish the chunked uploading, so it's not similar _enough_.

Sorry @XiaoningLiu, I've grown accustomed to a lot of close-enough and workarounds with azure, so I have to be very firm in saying your suggestion just doesn't suit my needs.  I really wish the product teams at Azure would get better at anticipating and being prepared for a variety of use cases in their products.  I think a more holistic approach would go a long way to address so many offerings on Azure coming out half-baked and missing crucial core functionality that competitors not only offer, but were proactive enough to have from day one.

**Comment by atrauzzi** [comment]
Following up again because I still really need the ability to create presigned upload URIs for individual file paths, similar to what AWS S3 offers.

SAS is not equivalent and I do not wish to grant clients access to the **entire blob**.  I only wish for them to be able to upload files with a specific path in the blob using URIs I generate server-side.

**Comment by XiaoningLiu** [comment]
Hi @atrauzzi , please open your proposal here https://feedback.azure.com/forums/217298-storage, and vote for it. Storage team will pick up customer requirements into our next planning!

**Comment by atrauzzi** [comment]
Not encouraging as this makes me think it could be a long time (1+ years) before this feature is ever implemented.  Hopefully you pick it up proactively with some urgency: https://feedback.azure.com/forums/217298-storage/suggestions/37773631-support-presigned-requests-for-individual-blobs-ke

**Comment by XiaoningLiu** [comment]
Sorry for the inconvenience, this is not a SDK feature. while it needs service support, storage team sure will pick up valuable items for investigation and to the development plan.

BTW, why not creating SAS URLs for different block blobs and assign to different clients? So every client can only upload to 1 blockblob. When they all finishes, the server can manage all the uploaded blobs.

**Comment by katmsft** [comment]
Since it is a storage feature, and not related to the SDK itself, we will close the issue fro now. Thanks for raising the feature request!

**Comment by matrey** [comment]
@atrauzzi Regarding this:

> SAS is not equivalent and I do not wish to grant clients access to the entire blob. I only wish for them to be able to upload files with a specific path in the blob using URIs I generate server-side.

My understanding is that for Azure Blob storage, "blob" is the actual object / file (under a path ("container"), inside a bucket ("storage account")). So blob-level permissions seem fine-grained enough.

For instance https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas

> Canonicalized resource
> The canonicalizedresouce portion of the string is a canonical path to the signed resource.
> 
> Blob example
> URL = https://myaccount.blob.core.windows.net/music/intro.mp3  
> canonicalizedresource = "/blob/myaccount/music/intro.mp3"

**Comment by darcythomas** [comment]
@atrauzzi 

> Following up again because I still really need the ability to create presigned upload URIs for individual file paths, similar to what AWS S3 offers.
> 
> SAS is not equivalent and I do not wish to grant clients access to the **entire blob**. I only wish for them to be able to upload files with a specific path in the blob using URIs I generate server-side.

An Azure blob is roughly equivalent to an AWS S3 Object. (And an Azure blob container is roughly equivalent to an AWS S3 Bucket)

So for your scenario, you would need to create a SAS for a single Azure Blob (think file), share the SAS with the user, they then use that to upload with the php API which will handle all of the streaming/chunking. You can add an expires time when the user will not be able to upload any more. You can create a trigger on the container, which the blob will be put into, to let you know when it has finished uploading; and for you to then do further processing.


Does that help?

**Comment by atrauzzi** [comment]
Thanks @darcythomas!  I'll come back to all this once my hands are back in updating our upload handling.

**Comment by ddl-denis-parnovskiy** [comment]
How it can be done with Put Block API and SAS

1. When a client initiates an upload, it splits the file into n chunks.
2. It sends a request to my API server, informing that it has n chunks size chunkSize + lastChunkSize.
3. The API server performs an authorization check according to my own domain and then responds with  an array of generated "Put Block" URLs (https://docs.microsoft.com/en-us/rest/api/storageservices/put-block). Each of them has Put block URI + SAS parameters. 
4. The client receives these URLs and sends one HTTP PUT request for each part using given URL.
5. After uploading each chunk, the client informs my API that the pieces are ready. My API server executes "Put Block List" against Azure.
6. The binary data is now available for my API to manipulate, such as transferring bucket-to-bucket

Difference from S3:
-  Put block PUT request doesn't return eTag to the client. If you want your client to be cross-platform, it should work with empty eTag from part upload.
- You cannot presign headers like MD5, content-type, etc.

Correct me if I'm wrong
