### ISSUE TITLE
How to access to Azure File Storage file properties

### ISSUE THREAD

**Issue by Karrtojal** [Azure/azure-storage-php#189]
List the folders and files with 
$listResult = $fileRestProxy->ListDirectoriesAndFiles($shareName,$path,$options);
gets the files and directories. 
Is there any way to get the FileProperties?
$arrFiles = $listResult->getFiles();
$arrDir = $listResult->getDirectories();
foreach ($arrFiles as $file)
{
   $name = $file->getName();
   $length = $file->getLength();
   // How to get the FileProperties? 
}

It should be a $properties variable in the File class to access.
Regards.

**Comment by katmsft** [comment]
According to the [REST API specification](https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files) for list directories and files, only content-length is in the file properties. If you need the file's properties, call `getFileProperties` instead.

**Comment by Karrtojal** [comment]
Ok, thanks katmsft!! 
Regards
