### ISSUE TITLE
generateFileDownloadLinkWithSAS with especial characteres file names

### ISSUE THREAD

**Issue by Karrtojal** [Azure/azure-storage-php#190]
### Which service(blob, file, queue, table) does this issue concern?
File

### Which version of the SDK was used?
Microsoft Azure Storage File PHP Client Library

### What's the PHP/OS version?
7.3

### What problem was encountered?
Using the https://github.com/Azure/azure-storage-php/blob/master/samples/FileSamples.php example to generate an URL with SAS (generateFileDownloadLinkWithSAS) Works perfectly with normal names, but this one for example fails.
{sharename}/A1/eñe20!'.pdf
{sharename}/A1/21883,€823 ñaño020!'.pdf
etc
With these characteres doesn't work. I've tried to encode the files and other combinations withtout results:
    $prepareFilePath = implode('/', array_map(function ($v)
    {
        return rawurlencode($v);
    }, explode('/', $filePath))
    );

$sas = $helper->generateFileServiceSharedAccessSignatureToken(
        Resources::RESOURCE_TYPE_FILE,
        $shareName . "/" . $prepareFilePath,
        'r',     // Read
        $endDate // '2020-01-01T08:30:00Z'      // A valid ISO 8601 format expiry time
        );
...
$fileUrlWithSAS = sprintf(
        '%s%s?%s',
        (string)$fileClientWithSAS->getPsrPrimaryUri(),
        $shareName . "/" . $prepareFilePath,
        $sas
        );

### Steps to reproduce the issue?
upload in a share a folder and a file with special characteres:
file: 21883,€823 ñaño020!'.pdf
file: eñe20!'.pdf
folder: B. ñañs93!€&%$
etc

### Have you found a mitigation/solution?
No

**Comment by katmsft** [comment]
Have you tried to URL encode the names and see if it works?

**Comment by Karrtojal** [comment]
Yes, In the code you can see rawurlencode. I've tried with urlencode, utf8_encode, utf8_decode, etc.

**Comment by katmsft** [comment]
#193 should be able to fix this issue. Thanks for reporting.

**Comment by katmsft** [comment]
Correction: Fixed by #202 .

**Comment by katmsft** [comment]
The fix is now in the latest release, check it out!
