### ISSUE TITLE
Cannot create files from empty contents

### ISSUE THREAD

**Issue by jgallred** [Azure/azure-storage-php#197]
### Which service(blob, file, queue, table) does this issue concern?
file

### Which version of the SDK was used?
microsoft/azure-storage-file 1.2.1
microsoft/azure-storage-common 1.4.0

### What's the PHP/OS version?
Tested on PHP 7.3.11 on Ubuntu 16 and PHP 7.2.14 on Azure's Debian 9 backports image

### What problem was encountered?
The `createFileFromContent*` methods accept an argument of `$content`, but if that argument is empty (for example an empty string or a stream from another empty file) then the Files API returns an error that the signature is invalid (using the shared key auth scheme).

    PHP Fatal error:  Uncaught MicrosoftAzure\Storage\Common\Exceptions\ServiceException: Fail:
    Code: 403
    Value: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
    details (if any): ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
    RequestId:00958cea-c01a-00bd-5dec-983e71000000
    Time:2019-11-12T00:01:22.0312583Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '<REDACTED SIGNATURE>' is not the same as any computed signature. Server used following string to sign: 'PUT
    
    
    
    
    
    Tue, 12 Nov 2019 00:01:21 GMT
    
    
    
    
    
    x-ms-range:bytes=0--1
    x-ms-request-id:5dc9f651f396a
    x-ms-version:2016-05-31
    x-ms-write:Update
    /<REDACTED STORAGE ACCOUNT>/<REDACTED FILE SHARE>/empty_5dc9f6518d11f.txt
    comp:range'.</AuthenticationErrorDetail></Error>. in vendor/microsoft/azure-storage-common/src/Common/Internal/ServiceRestProxy.php on line 490

The empty file is successfully created by the underlying call to `createFileAsync`, but the subsequent call to `putFileRangeAsync` is what breaks the code. Interestingly, the signing string generated by the library includes the 0 on a line for the content-length, which differs from the server generated value. I've fiddled with the underlying code and even tested the node library trying to understand. As near as I can tell, uploading an empty range simply isn't supported by the Files API. That's fine, but I think that the library could make it less of an issue with a small code change.

### Steps to reproduce the issue?
I wrote the following PHP script to replicate the issue and debug.

    <?php
    
    require_once __DIR__ . '/vendor/autoload.php';
    
    $storage_account = '';
    $file_share = '';
    $access_key = '';
    $client = \MicrosoftAzure\Storage\File\FileRestProxy::createFileService("DefaultEndpointsProtocol=https;AccountName=$storage_account;AccountKey=$access_key");
    $client->createFileFromContent($file_share, uniqid('empty_') . '.txt', '');

### Have you found a mitigation/solution?
Modifying `createFileFromContentAsync` to handle 0 size files would completely resolve the exception. 

    public function createFileFromContentAsync(
        $share,
        $path,
        $content,
        CreateFileFromContentOptions $options = null
    ) {
        $stream = Psr7\stream_for($content);
        $size = $stream->getSize();

        if ($options == null) {
            $options = new CreateFileFromContentOptions();
        }

        //create the file first
        $promise = $this->createFileAsync($share, $path, $size, $options);

        //then upload the content
        $range = new Range(0, $size - 1);
        $putOptions = new PutFileRangeOptions($options);
        $useTransactionalMD5 = $options->getUseTransactionalMD5();
        if ($size > Resources::MB_IN_BYTES_4) {
            return $promise->then(function ($response) use (
                $share,
                $path,
                $stream,
                $range,
                $putOptions,
                $useTransactionalMD5
            ) {
                return $this->multiplePutRangeConcurrentAsync(
                    $share,
                    $path,
                    $stream,
                    $range,
                    $putOptions,
                    $useTransactionalMD5
                );
            }, null);
        } elseif ($size > 0) { // <-- NEW: Only try to upload a range if there is a range to upload
            return $promise->then(function ($response) use (
                $share,
                $path,
                $stream,
                $range,
                $putOptions
            ) {
                return $this->putFileRangeAsync(
                    $share,
                    $path,
                    $stream,
                    $range,
                    $putOptions
                );
            }, null);
        } else {
             // NEW: Otherwise, just create the empty file
            return $promise;
        }
    }

**Comment by katmsft** [comment]
Thank you very much for the detailed investigation and suggestion. This is identified as a bug and I will submit a PR to fix it soon.

**Comment by katmsft** [comment]
Fixed by #201

**Comment by jgallred** [comment]
Thanks @katmsft!

**Comment by katmsft** [comment]
The fix is now in the latest release, check it out!
