### ISSUE TITLE
Connection string with SAS is causing error

### ISSUE THREAD

**Issue by tiagoa** [Azure/azure-storage-php#198]
### Which service(blob, file, queue, table) does this issue concern?
File

### Which version of the SDK was used?
1.4.0

### What's the PHP/OS version?
PHP 7.1.27
OS Ubuntu 18.04

### What problem was encountered?
Try to connect with a connection string without AccountKey but with SAS is returning an invalid connection string, even when I'm using a valid one:

### Steps to reproduce the issue?
```php
<?php
$connectionString = sprintf(
 'DefaultEndpointsProtocol=https;AccountName=%s;FileEndpoint=%s;SharedAccessSignature=%s',
  'myaccount',
  'https://myaccount.file.core.windows.net',
  'sv=2018-03-28&si=app-write-policy&sr=s&sig=mysig'
);

$driverConfig = [
  'endpoint' => $connectionString,
  'container' => 'mycontainer',
  'disableRecursiveDelete' => !empty($config['myconfig']),
];

$fileService = FileRestProxy::createFileService($connectionString);
```
### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
How about this format? `BlobEndpoint=myBlobEndpoint;QueueEndpoint=myQueueEndpoint;TableEndpoint=myTableEndpoint;FileEndpoint=myFileEndpoint;SharedAccessSignature=sasToken`

**Comment by tiagoa** [comment]
Unfortunately did not work.
```
The provided connection string 'DefaultEndpointsProtocol=https;AccountName=myaccount;BlobEndpoint=https://myaccount.blob.core.windows.net;QueueEndpoint=https://myaccount.queue.core.windows.net;TableEndpoint=https://myaccount.table.core.windows.net;FileEndpoint=https://myaccount.file.core.windows.net;SharedAccessSignature=sv=2018-03-28&si=app-write-policy&sr=s&sig=mysig' does not have complete configuration settings.
```

**Comment by tiagoa** [comment]
Providing just
```
FileEndpoint=myFileEndpoint;SharedAccessSignature=sasToken
```
worked.
