### ISSUE TITLE
Warning: Invalid argument supplied for foreach() Blob/Models/BlockList.php on line 165

### ISSUE THREAD

**Issue by talilon** [Azure/azure-storage-php#199]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### What's the PHP/OS version?
PHP 7.2/CentOS

### What problem was encountered?
The following error is generated when trying to upload a file that is larger than "SingleBlobUploadThresholdInBytes"

Warning: Invalid argument supplied for foreach() in MicrosoftAzure/Storage/Blob/Models/BlockList.php on line 165

### Steps to reproduce the issue?

```
$blobConnection = BlobRestProxy::createBlobService($connectionString);
$blobConnection->createBlockBlob($containerName, $blobName, $fileResource);
```
Where $fileResource is pointing to a file larger than SingleBlobUploadThreashholdInBytes.

### Have you found a mitigation/solution?
If I increase SingleBlobUploadThreashholdInBytes to be larger than the file I'm uploading, it works.
```
$blobConnection->setSingleBlobUploadThresholdInBytes(4444444444);
```

**Comment by XiaoningLiu** [comment]
Thanks for reporting! That's not expected, will check what happens.

**Comment by talilon** [comment]
This was an issue with my code and was caused by passing in a tmp file resource after writing to it without resetting the pointer to the beginning of the file. 

Resetting the pointer to 0 for $fileResource  before calling createBlockBlob resolves the issue.
