### ISSUE TITLE
Cannot upload well known audio formats

### ISSUE THREAD

**Issue by jgallred** [Azure/azure-storage-php#200]
### Which service(blob, file, queue, table) does this issue concern?
file

### Which version of the SDK was used?
microsoft/azure-storage-file 1.2.1
microsoft/azure-storage-common 1.4.0

### What's the PHP/OS version?
Tested on PHP 7.3.11 on Ubuntu 16 and PHP 7.2.14 on Azure's Debian 9 backports image

### What problem was encountered?
The library is unable to upload well known audio file types (mp3, wav) because the Files API returns an error that the signature is invalid (using the shared key auth scheme). A gsm type audio file uploads fine. We believe the error is occurring because the Files API is interpreting the contents of the uploaded File Range based on any present audio content header and generating an HTTP content-type header value for the server-side signature when none was given by the client.

String to sign generated by client:
```
PUT


87884


Wed, 04 Dec 2019 17:18:34 GMT





x-ms-range:bytes=0-87883
x-ms-request-id:5de7ea6a72d1e
x-ms-version:2016-05-31
x-ms-write:Update
/<REDACTED STORAGE ACCOUNT>/<REDACTED FILE SHARE>/test5de7ea69ebe4f.wav
comp:range
```

Error
```
PHP Fatal error:  Uncaught MicrosoftAzure\Storage\Common\Exceptions\ServiceException: Fail:
Code: 403
Value: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. details (if any): ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:0a937dd7-801a-00d6-80c6-aaad69000000
Time:2019-12-04T17:18:34.5120347Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '<REDACTED SIGNATURE>' is not the same as any computed signature. Server used following string to sign: 'PUT


87884

audio/x-wav
Wed, 04 Dec 2019 17:18:34 GMT





x-ms-range:bytes=0-87883
x-ms-request-id:5de7ea6a72d1e
x-ms-version:2016-05-31
x-ms-write:Update
/<REDACTED STORAGE ACCOUNT>/<REDACTED FILE SHARE>/test5de7ea69ebe4f.wav
comp:range'.</AuthenticationErrorDetail></Error>. in vendor/microsoft/azure-storagecommon/src/Common/Internal/ServiceRestProxy.php on line 490
```

The files are created in the storage account and claim to have a file size, but if you download them they cannot play.

### Steps to reproduce the issue?
I wrote the following PHP script to replicate the issue and debug. 

[test audio files.zip](https://github.com/Azure/azure-storage-php/files/3923276/test.audio.files.zip)

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

$storage_account = '';
$file_share = '';
$access_key = '';
$client = \MicrosoftAzure\Storage\File\FileRestProxy::createFileService("DefaultEndpointsProtocol=https;AccountName=$storage_account;AccountKey=$access_key");


// Will break
$rd = fopen(__DIR__ . '/test.wav', 'r');
$client->createFileFromContent($options['file_share'], uniqid('test') . '.wav', $rd);

// Will break
// $rd = fopen(__DIR__ . '/test.mp3', 'r');
// $client->createFileFromContent($options['file_share'], uniqid('test') . '.mp3', $rd);

// Uploads fine
// $rd = fopen(__DIR__ . '/test.gsm', 'r');
// $client->createFileFromContent($options['file_share'], uniqid('test') . '.gsm', $rd);
```
### Have you found a mitigation/solution?
I have a hard time telling whether the burden should rest on the Files API or on the calling PHP code.

If the Files API just respected the headers sent by the client instead of generating them by reading the payload data, I don't think there would be an issue.

It would be possible for the PHP code to set the header for the PUT File Range request and succeed, but the library does not support setting that header. The `createFileFromContent`* methods accept options via an instance of `CreateFileFromContentOptions`. The `CreateFileFromContentOptions` class has a property for Content-Type, however this value is only used when generating the Content-Type header for the `createFileAsync` call. The subsequent 
call to `putFileRangeAsync` requires an instance of `PutFileRangeOptions`, but `PutFileRangeOptions` has no content-type property to set. If it did, then callers could conceivably extract the MIME type of the file themselves and perform the file creation and range upload manually.

```
<?php
...
namespace MicrosoftAzure\Storage\File\Models;
...
class PutFileRangeOptions extends FileServiceOptions
{
    private $contentMD5;
    private $contentType;
    ...
    public function getContentType()
    {
        return $this->contentType;
    }

    public function setContentType($contentType)
    {
        $this->contentType = $contentType;
    }
}
```

```
<?php
...
namespace MicrosoftAzure\Storage\File;
...
class FileRestProxy extends ServiceRestProxy implements IFile
{
    ...
    public function putFileRangeAsync(
        $share,
        $path,
        $content,
        Range $range,
        PutFileRangeOptions $options = null
    ) {
        ...
        $this->addOptionalHeader(
            $headers,
            Resources::CONTENT_TYPE,
            $options->getContentType()
        );
        ...
    }
    ...
}
```

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

$storage_account = '';
$file_share = '';
$access_key = '';
$client = \MicrosoftAzure\Storage\File\FileRestProxy::createFileService("DefaultEndpointsProtocol=https;AccountName=$storage_account;AccountKey=$access_key");
$src_filename = __DIR__ . '/test.wav';
$size = filesize($src_filename);
$type = mime_content_type($src_filename);
$dst_filename = uniqid('test') . '.wav';
$client->createFile($options['file_share'], $dst_filename, $size);
$rd = fopen($src_filename, 'r');
$opts = new \MicrosoftAzure\Storage\File\Models\PutFileRangeOptions();
$opts->setContentType($type);
$range = new \MicrosoftAzure\Storage\Common\Models\Range(0, $size - 1);
$client->putFileRange($options['file_share'], $dst_filename, $rd, $range, $opts);
```

**Comment by XiaoningLiu** [comment]
Hi @jgallred Your investigation is very detail and helpful. 

To upload a file, there are 2 kinds of REST APIs will be triggerred, mapping to 2 PHP methods you mentioned:
* [Create File](https://docs.microsoft.com/en-us/rest/api/storageservices/create-file) -> `createFileAsync `
* [Put File Range](https://docs.microsoft.com/en-us/rest/api/storageservices/put-range) -> `putFileRangeAsync`

`Create File` supports content-type header, while `Put File Range` RESTful API doesn't. So `putFileRangeAsync` should not set content type header in the HTTP request.

The issue is why `audio/x-wav` header is added while `putFileRangeAsync` doesn't explicitly set it.

**Comment by jgallred** [comment]
Works wonderfully. Thank you @XiaoningLiu!
