### ISSUE TITLE
Support File Storage

### ISSUE THREAD

**Issue by justincy** [Azure/azure-storage-php#21]
https://azure.microsoft.com/en-us/services/storage/files/

**Comment by nowenL** [comment]
Thx. It's already in our road map.

**Comment by jordonbrill** [comment]
Is there any updates on this or any ability for the community to contribute?

**Comment by katmsft** [comment]
It is one of prioritized feature that we are going to support in the future.

**Comment by jordonbrill** [comment]
Awesome. Thanks for the update!

**Comment by seguler** [comment]
I was wondering whether you could explain your scenarios. File service is more positioned for mounting a filesystem as a disk through SMB, whereas the same (and added) functionality can be found in Blob service where we have better support in our client libraries/REST API. Is there a reason why you choose Files over Blobs, and need the support in the SDK ? Why not use blobs if you are only accessing your storage through a program ?

**Comment by justincy** [comment]
> I was wondering whether you could explain your scenarios. File service is more positioned for mounting a filesystem as a disk through SMB, whereas the same (and added) functionality can be found in Blob service where we have better support in our client libraries/REST API. Is there a reason why you choose Files over Blobs, and need the support in the SDK ? Why not use blobs if you are only accessing your storage through a program ?

I didn't know all that. I just thought it was strange to have an SDK that didn't support a portion of the API.

**Comment by seguler** [comment]
Ok - thanks for responding. We will support it in the future, but we were contemplating whether to prioritize other things before Files, like support for large block blobs (5TB), and other things mentioned here: https://github.com/Azure/azure-storage-php/issues/78

**Comment by katmsft** [comment]
File service is fully supported in 0.16.0. @justincy @jordonbrill check it out.

**Comment by vipin-chand** [comment]
@katmsft I don't see any document for this.

**Comment by katmsft** [comment]
@vipin-chand What kind of document? You can find the auto-generated doc [here](http://azure.github.io/azure-storage-php/) or the REST API in the original post.

**Comment by charlesrthompsonindy** [comment]
@katmsft Is there a example for using the newly exposed SAS functions in tandem with the File service?

**Comment by katmsft** [comment]
@charlesrthompsonindy Actually we did not write any samples for using the two newly added features, but you can always reference `MicrosoftAzure\Storage\Tests\functional\Common\ServiceSASFunctionalTest::testFileServiceSAS` for detailed information of how are we suppose to generate and use the SAS token. I have created a backlog item to write samples to use account level SAS and service level SAS. Thanks.

**Comment by katmsft** [comment]
No response for a month, suggest to close the issue.
