### ISSUE TITLE
public function createContainer returns void !

### ISSUE THREAD

**Issue by picks44** [Azure/azure-storage-php#211]
### Which service(blob, file, queue, table) does this issue concern?
BLOB

### What problem was encountered?
public function createContainer in BlobRestProxy class returns void !

### Have you found a mitigation/solution?
return a boolean maybe ?

**Comment by ecourtial** [comment]
It seems it throws an exception if something fails.
ServiceRestProxy::sendAsync()
Did you encounter any use case where the container creation failed without having an exception?

**Comment by picks44** [comment]
@ecourtial Nope, but it just seems weird to me that a function like this would return a void in case of success...

**Comment by XiaoningLiu** [comment]
Hi, it's by design to return void. Some design pattern may use return value as inditator of operation success or not, while this repo uses exception.

**Comment by picks44** [comment]
Understood. I'll use a try {} catch (Exception $e) {} then. Thanks!
