### ISSUE TITLE
Can't get list Blob

### ISSUE THREAD

**Issue by mrofisr** [Azure/azure-storage-php#215]
### Which service(blob, file, queue, table) does this issue concern?
 Blob

### Which version of the SDK was used?
New Version

### What's the PHP/OS version?
PHP 7
Ubuntu

### What problem was encountered?
Can't get list of Blob

Class 'SimpleXMLElement' not found in vendor/microsoft/azure-storage-common/src/Common/Internal/Serialization/XmlSerializer.php:241

(If you think some of the information should not be shared publicly, you can e-mail the main Microsoft contributors of the repository instead.)

**Comment by XiaoningLiu** [comment]
Hi @mrofisr Sorry for the late response due to the holiday season. Can you help provide sample code to reproduce this?
