### ISSUE TITLE
FileRestProxy set empty content_type which not worked on curl 7.58.0

### ISSUE THREAD

**Issue by ronnydeter** [Azure/azure-storage-php#221]
### Which service(blob, file, queue, table) does this issue concern?
File 

### Which version of the SDK was used?
1.2.2

### What's the PHP/OS version?
(PHP 7.2.26-1+ubuntu18.04.1+deb.sury.org+1)/Linux

### What problem was encountered?
FileRestProxy.php has on line 2281 a code 
// Stop Guzzle adding content-type header which may block SharedKey authentication
$headers[Resources::CONTENT_TYPE] = Resources::EMPTY_STRING;
which sends with the curl 7.58.0 two times the content_type header.
The endpoint of the API will give a 400 Bad Request back.
When I comment the line out, the file will be created and everything works fine.

### Steps to reproduce the issue?
< HTTP/1.1 201 Created
< Content-Length: 0
< Last-Modified: Mon, 10 Feb 2020 11:55:23 GMT
< ETag: "0x8D7AE201C716990"
< Server: Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: 9bba0f0f-301a-005c-7708-e0a83d000000
< x-ms-version: 2016-05-31
< Date: Mon, 10 Feb 2020 11:55:22 GMT
< 
* Connection #0 to host mgisdevstorage.file.core.windows.net left intact
* Found bundle for host mgisdevstorage.file.core.windows.net: 0x556bf4c47110 [can pipeline]
* Re-using existing connection! (#0) with host mgisdevstorage.file.core.windows.net
* Connected to mgisdevstorage.file.core.windows.net (40.68.232.60) port 443 (#0)
> PUT /files/connection_223/contract/336184887/bb6d9f50cda8bb9ce28bae84310c996e.pdf?comp=range HTTP/1.1
Host: mgisdevstorage.file.core.windows.net
x-ms-range: bytes=0-318509
x-ms-write: Update
content-type:      <- empty String is set by FileRestProxy
x-ms-version: 2016-05-31
User-Agent: Azure-Storage/1.2.2-1.4.0 (PHP 7.2.26-1+ubuntu18.04.1+deb.sury.org+1)/Linux
date: Mon, 10 Feb 2020 11:55:29 GMT
x-ms-request-id: 5e4144b1b3fcf
authorization: SharedKey mgisdevstorage:*********
Content-Length: 318510
Content-Type: application/x-www-form-urlencoded

< HTTP/1.1 400 Bad Request
< Content-Type: text/html; charset=us-ascii
< Server: Microsoft-HTTPAPI/2.0
< Date: Mon, 10 Feb 2020 11:55:29 GMT
< Connection: close
< Content-Length: 339
< 
* we are done reading and this is set to close, stop send
* Closing connection 0 
### Is there a failing request ID related to this problem returned by server? What is it?
x-ms-request-id: 5e4144b1b3fcf

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)
date: Mon, 10 Feb 2020 11:55:29 GMT
x-ms-request-id: 5e4144b1b3fcf
mgisdevstorage.file.core.windows.net

(If you think some of the information should not be shared publicly, you can e-mail the main Microsoft contributors of the repository instead.)

**Comment by katmsft** [comment]
Hi, thanks for bringing up the issue and provide a very thorough investigation. We will put the bugfix into our backlog.

**Comment by eddedre** [comment]
Thanks for reporting this as I also have the issue
