### ISSUE TITLE
Create SAS token for polybase export

### ISSUE THREAD

**Issue by zajca** [Azure/azure-storage-php#226]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
1.5.0

### What's the PHP/OS version?
PHP 7.1 - Linux

### What problem was encountered?
I'm having troube with creating right token for polybase external table. If I create External table and add more permissions than `w` token is longer than 120 characters. And polybase will fail. With token with just `w` token has 120 chars but does not work.

This not actually bug, sas token works in general, but not in polybase.

### Steps to reproduce the issue?

I'm creating token with `BlobSharedAccessSignatureHelper`
```php
$sasHelper = new BlobSharedAccessSignatureHelper(
            (string) getenv('ABS_ACCOUNT_NAME'),
            (string) getenv('ABS_ACCOUNT_KEY')
        );
        $expirationDate = (new DateTime())->modify('+1hour');
        $token = $sasHelper->generateBlobServiceSharedAccessSignatureToken(
            Resources::RESOURCE_TYPE_CONTAINER,
            'mycontainer',
            'r',
            $expirationDate,
            (new DateTime())
        );
$token = urldecode($token);
```
These are queries that I run after:

```sql
CREATE DATABASE SCOPED CREDENTIAL [EXPORT_Credential]
WITH
    IDENTITY = 'SHARED ACCESS SIGNATURE',
    SECRET = 'sas token'
;

CREATE EXTERNAL DATA SOURCE [EXPORT_Source]
WITH
    (
        TYPE = HADOOP,
        LOCATION = 'wasbs://mycontainer@account.blob.core.windows.net/',
        CREDENTIAL = [EXPORT_Credential]
    );

CREATE EXTERNAL FILE FORMAT [EXPORT_FileFormat]
WITH
    (
        FORMAT_TYPE = DelimitedText,
        FORMAT_OPTIONS
        (
        FIELD_TERMINATOR = ',',
        STRING_DELIMITER = '"',
        DATE_FORMAT = 'yyyy-MM-dd HH:mm:ss',
        USE_TYPE_DEFAULT = FALSE
        ),
        DATA_COMPRESSION = 'org.apache.hadoop.io.compress.DefaultCodec'
    );

CREATE EXTERNAL TABLE [EXPORT_ExternalTable]
WITH
    (
        LOCATION='test_export/ts_test',
        DATA_SOURCE = [EXPORT_Source],
        FILE_FORMAT = [EXPORT_FileFormat]
    )
    AS
SELECT * FROM [in_table]';
```

If I create token with `w` permissions I get:
`External file access failed due to internal error: 'Parameters provided to connect to the Azure storage account are not valid.'`

If I create token with more permisions like `rwl`:
`Secret provided can not contain more than 120 characters. Please provide a valid credential.`

**Comment by katmsft** [comment]
Thanks for raising the issue. Please stay tuned while we investigate this issue.

**Comment by zajca** [comment]
Sorry did wrongly read documentation. 

It stands:
`To load from Azure Blob storage into SQL DW or Parallel Data Warehouse, the Secret must be the Azure Storage Key.`

End in examples:
`Shared Access Signatures cannot be used with PolyBase in SQL Server, APS or SQL DW.`

I was kind of confused with all examples using "SHARED ACCESS SIGNATURE" in "IDENTITY".
