### ISSUE TITLE
The `client-request-id` value is missing from logs.

### ISSUE THREAD

**Issue by ScottHelme** [Azure/azure-storage-php#231]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
1.1.2

### What's the PHP/OS version?
PHP 7.3 / Ubuntu 16.04

### What problem was encountered?
The `<client-request-id>` is missing from Azure logs.

### Steps to reproduce the issue?
Make any request to Table Storage, extract logs, `<client-request-id>` is missing from logs.

### Have you found a mitigation/solution?
No.

### Is there a failing request ID related to this problem returned by server? What is it?
Can email information if needed. 

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)
This is happening at present, can email other info.

**Comment by ScottHelme** [comment]
I saw your comment [here](https://github.com/Azure/azure-storage-php/issues/222) @XiaoningLiu, should we expect this value to be present in Azure logs?

**Comment by XiaoningLiu** [comment]
Hi @ScottHelme Sorry for miss this. Are you referring to logs generated by storage PHP SDK, or other "Azure logs"?

**Comment by ScottHelme** [comment]
Hey @XiaoningLiu, I'm looking at the logs that are generated and stored in Blob storage and are configured in the Diagnostic Settings section of my storage account. 

The [log entry fields](https://docs.microsoft.com/en-gb/rest/api/storageservices/storage-analytics-log-format#log-entry-fields-for-version-10) indicate that `<client-request-id>` should be present in the logs but we are seeing an empty field in all of our logs.

**Comment by XiaoningLiu** [comment]
Understand your question. Can you share me a <request-id-header> (x-ms-request-id) in your Azure Logs to me? I can take a look. The <request-id-header> better in 2 days.

**Comment by ScottHelme** [comment]
Here is one of our latest log entries with items redacted:

```
1.0;2020-06-23T09:11:27.9274972Z;QueryEntities;Success;200;3;3;authenticated;reporturi;reporturi;table;"[redacted]";"/reporturi";813291ba-7002-010d-363e-499130000000;0;165.22.149.175:53140;2016-05-31;537;0;255;90;0;;;;;;"Azure-Storage/1.1.2-1.4.1 (PHP 7.3.17-1+ubuntu18.04.1+deb.sury.org+1)/Linux";;
```

**Comment by XiaoningLiu** [comment]
@ScottHelme I can see your request doesn't include client request ID. Marked this as bug of PHP SDK.

**Comment by katmsft** [comment]
This will be released with a merged PR in the next release upcoming in Aug.
