### ISSUE TITLE
Argument 4 passed to MicrosoftAzure\Storage\Common\Internal\ServiceRestProxy::__construct() must be of the type array, object given, called in C:\xampp\htdocs\DistanceApp\DS.Web\vendor\microsoft\azure-storage\src\Common\ServicesBuilder.php on line 258&#039; 

### ISSUE THREAD

**Issue by sanjayhais** [Azure/azure-storage-php#232]
public static function uploadBlob($myContainer, $blob_name, $content)
    {
        $connectionString ="my connection string "

        $blobClient = ServicesBuilder::getInstance()->createBlobService($connectionString);

        try {
            //Upload blob

            $blobClient->createBlockBlob($myContainer, $blob_name, $content);
        } catch (ServiceException $e) {
            $code = $e->getCode();
            $error_message = $e->getMessage();
            echo $code . ": " . $error_message . PHP_EOL;
        }
    }

**Comment by katmsft** [comment]
Can you please elaborate on this issue? Is the exception thrown on line `$blobClient = ServicesBuilder::getInstance()->createBlobService($connectionString);`? What version of the SDK are you using?

**Comment by lrauldan** [comment]
I have the same issue. As the 4th constructor argument of `MicrosoftAzure\Storage\Common\Internal\ServiceRestProxy`an instance of `XmlSerializer` is passed instead of the array `$options`.

**Comment by lrauldan** [comment]
@ sanjayhais, I had the same issue. Take a look at your composer dependencies, you probably have "microsoft/windowsazure" listed as a requirement. Start by removing that as it conflicts with this package.

**Comment by sanjayhais** [comment]
Thanks ... it works  + I used BlobRestProxy::createBlobService($connectionString); to generate instance instead of ServicesBuilder::getInstance()->createBlobService($connectionString);
