### ISSUE TITLE
Blob storage QP_PREFIX appears to need "Prefix" to be lowercased

### ISSUE THREAD

**Issue by subhaze** [Azure/azure-storage-php#235]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
1.5

### What's the PHP/OS version?
7.3/Docker

### What problem was encountered?
`setPrefix` does not behave correctly, at least while using the mcr.microsoft.com/azure-storage/azurite emulation image

### Steps to reproduce the issue?
- Setup a container with two folders and a file each (foldera/foo.tx, folderb/bar.txt)
- Use setPrefix("foldera") on a `ListBlobsOptions` instance
- when `listBlobs(container, options)` is called, all blobs are listed

### Have you found a mitigation/solution?

Update QP_PREFIX from `Prefix` to `prefix`

After this was updated locally the prefix filtering began working and returning only blobs matching the prefix.

https://github.com/Azure/azure-storage-php/blob/cdb39bd06386d90e28bae8511b033681b4dcbf0e/azure-storage-common/src/Common/Internal/Resources.php#L248

### Is there a failing request ID related to this problem returned by server? What is it?
no

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)

devstoreaccount1

**Comment by katmsft** [comment]
Hi, thanks for reporting the issue!

Just tried in production, this seems to be a issue on azurite, not PHP SDK.

**Comment by XiaoningLiu** [comment]
Releated query parameter values have been lower cased in 1.5.0 common package release.
