### ISSUE TITLE
MarkerContinuationTokenTrait.php: getContinuationToken() has wrong return type

### ISSUE THREAD

**Issue by subhaze** [Azure/azure-storage-php#237]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
1.5

### What's the PHP/OS version?
7.3/Docker (macOS)

### What problem was encountered?
Wrong type returned within DocBlock comment

### Steps to reproduce the issue?

On line https://github.com/Azure/azure-storage-php/blob/5c4839e8d0bc5b0e8216fda745b0ac52130fd2bc/azure-storage-common/src/Common/MarkerContinuationTokenTrait.php#L66 it states that a `ContinuationToken` is returned but it appears this should be `MarkerContinuationToken` instead.

https://github.com/Azure/azure-storage-php/blob/5c4839e8d0bc5b0e8216fda745b0ac52130fd2bc/azure-storage-common/src/Common/MarkerContinuationTokenTrait.php#L58.

**Comment by XiaoningLiu** [comment]
Thanks @subhaze! We should update PHPDoc for MarkerContinuationToken. In the same time, contribution welcome!
