### ISSUE TITLE
Crash (Call to a member function getStatusCode() on null) on successful connection but no response

### ISSUE THREAD

**Issue by spaze** [Azure/azure-storage-php#242]
### Which service(blob, file, queue, table) does this issue concern?
Table/Blob

### Which version of the SDK was used?
blob 1.5.0
table 1.1.2
common 1.4.1

### What's the PHP/OS version?
PHP 7.3/Linux

### What problem was encountered?
Sometimes, we get the following error:
> PHP Error:  Call to a member function getStatusCode() on null in .../vendor/microsoft/azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php on line 179

https://github.com/Azure/azure-storage-php/blob/5c4839e8d0bc5b0e8216fda745b0ac52130fd2bc/azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php#L172-L181

Not sure why but I've been able to simulate it by using `TableEndpoint=http://127.0.0.1:12300` in the connection string and running `netcat -l -p 12300` and closing the connection after it has been established and sending some headers back.

In such cases `$exception->getResponse()` on line 173 returns null (docs says `getResponse()` can return null) and later `$response->getStatusCode()` but `$response` is null, so...

### Steps to reproduce the issue?
- Run `netcat -l -p 12300`
- Setup the service with the RetryMiddleware:
```php
$service = TableRestProxy::createTableService('DefaultEndpointsProtocol=https;TableEndpoint=http://127.0.0.1:12300;AccountName=bar;AccountKey=foo');
$service->pushMiddleware(RetryMiddlewareFactory::create(
	RetryMiddlewareFactory::GENERAL_RETRY_TYPE,
	3,
	1000,
	RetryMiddlewareFactory::EXPONENTIAL_INTERVAL_ACCUMULATION,
	true
));
```
- Run e.g. `$p->getTable('foo')`
- Wait for HTTP headers in the listening `netcat`
- While still in the `netcat` session, type `foo`, press Enter, `bar`, Ctrl+c
- Run `netcat -l -p 12300` again
- Wait for HTTP headers in the listening `netcat`
- While still in the `netcat` session, type `foo`, press Enter, `bar`, Ctrl+c
- Run `netcat -l -p 12300` again
- You get the idea

Far from perfect, but you should get the exception, if not try harder 😎

### Have you found a mitigation/solution?
Yes, I think that `$exception->getResponse()` returning `null` in `$response = $exception->getResponse();` should be handled because the Guzzle docs says it can return null so it's a valid scenario. Pull request incoming (#243).

### Is there a failing request ID related to this problem returned by server? What is it?
Unfortunately there isn't. The server, or something, closes the connection before any "Azure headers"

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)
reporturi 2020/07/10 21:21:38 UTC (timestamp from our app logging the `Error: Call to a member function getStatusCode() on null` error)

Thanks.

**Comment by XiaoningLiu** [comment]
@spaze Thanks for your detailed investigation and contribution!

**Comment by lksnmnn** [comment]
Were seeing this error now in production too. Any chance this gets released soon? If not we will need to checkout the **dev** branch.

**Comment by spaze** [comment]
@lksnmnn As per https://github.com/Azure/azure-storage-php/issues/207#issuecomment-658531592 and per the name of the milestone here https://github.com/Azure/azure-storage-php/milestone/1 there should be a new release this month. I'm eagerly awaiting one as well!

**Comment by lksnmnn** [comment]
So... will this be released this month? If not I'll need to fix this manually, as we are seeing this quite often on production now

**Comment by spaze** [comment]
@lksnmnn Seems the new release is being cooked right now, see #250 #251, expecting it every day Real Soon Now ™️. I hope the maintainers will make it 💪
