### ISSUE TITLE
Error: [Error] Undefined class constant 'SDK_VERSION' PHP7.1 Ubuntu 18.04

### ISSUE THREAD

**Issue by stuarteske** [Azure/azure-storage-php#246]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
azure-storage-blob Latest Stable Version 1.5.0

### What's the PHP/OS version?
uBuntu 18.0.4, php 7.1

### What problem was encountered?
2020-07-22 08:57:08 Error: [Error] Undefined class constant 'SDK_VERSION'
Request URL: /debug/upload
Stack Trace:
#0 /home/securepools/public_html/vendor/microsoft/azure-storage/src/Common/ServicesBuilder.php(211): MicrosoftAzure\Storage\Common\ServicesBuilder::getUserAgent()
#1 /home/securepools/public_html/app/Controller/DebugController.php(321): MicrosoftAzure\Storage\Common\ServicesBuilder->createBlobService('DefaultEndpoint...')
#2 [internal function]: DebugController->upload()
#3 /home/securepools/public_html/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(DebugController), Array)
#4 /home/securepools/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /home/securepools/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(DebugController), Object(CakeRequest))
#6 /home/securepools/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

### Steps to reproduce the issue?
    public function upload() {
        $this->autoRender = false;

        $connectionString = 'DefaultEndpointsProtocol=https;AccountName=<*******>;AccountKey=<******>;EndpointSuffix=core.windows.net';
        $blobClient = ServicesBuilder::getInstance()->createBlobService($connectionString);

        if (!file_exists("myfile.txt")) {
            $file = fopen("myfile.txt", 'w');
            fwrite($file, 'Hello World!');
            fclose($file);
        }

        $content = fopen("myfile.txt", "r");
        $blob_name = "myblob";

        $content2 = "string content";
        $blob_name2 = "myblob2";

        try {
            //Upload blob
            $myContainer = 'test';
            //$blobClient->createBlockBlob($myContainer, $blob_name, $content);
            //$blobClient->createBlockBlob($myContainer, $blob_name2, $content2);
        } catch (ServiceException $e) {
            $code = $e->getCode();
            $error_message = $e->getMessage();
            echo $code.": ".$error_message.PHP_EOL;
        }

        echo 'done';
    }

### Is there a failing request ID related to this problem returned by server? What is it?
this is a remotre php server to azure. there is no way to intercept this easily.

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)
Please see the stack trace above, Name p*******e

(If you think some of the information should not be shared publicly, you can e-mail the main Microsoft contributors of the repository instead.)

**Comment by XiaoningLiu** [comment]
azure-storage-blob doesn't have ServiceBuilder.php provided, can you double check if it's latest azure-storage-blob 1.5.0?

**Comment by stuarteske** [comment]
After playing with composer and libs I got it working. Thank you.
