### ISSUE TITLE
Fail: Code: 400 Value: Bad Request details (if any):

### ISSUE THREAD

**Issue by stuarteske** [Azure/azure-storage-php#247]
### Which service(blob, file, queue, table) does this issue concern?
File service

### Which version of the SDK was used?
azure-storage-file 1.2.2

### What's the PHP/OS version?
PHP7.1, Ubuntu 18.04

### What problem was encountered?
Fail: Code: 400 Value: Bad Request details (if any):
Bad Request - Invalid Header
HTTP Error 400. The request has an invalid header name.

File the filled with null data to the correct size.

### Steps to reproduce the issue?
public function putFileRange(
        $share,
        $path,
        $content,
        Range $range,
        FileModels\PutFileRangeOptions $options = null
    );

### Have you found a mitigation/solution?
NA

### Is there a failing request ID related to this problem returned by server? What is it?
NA

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)
p*******e

(If you think some of the information should not be shared publicly, you can e-mail the main Microsoft contributors of the repository instead.)

**Comment by XiaoningLiu** [comment]
@stuarteske Please share code for reproduce and server returned x-ms-request-id for further check. Following code example doesn't include API calls to storage PHP SDK.

```
public function putFileRange(
$share,
$path,
$content,
Range $range,
FileModels\PutFileRangeOptions $options = null
);
```

**Comment by stuarteske** [comment]
I changed versions and recieved a more informative error. However, I didn't fix this issue and moved over to the blob storage system.
