### ISSUE TITLE
Update "azure-storage-common" guzzle 6.0 dependency

### ISSUE THREAD

**Issue by sadika9** [Azure/azure-storage-php#248]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
1.5.0

### What's the PHP/OS version?
PHP 7.3

### What problem was encountered?
"azure-storage-blob package" depends on "azure-storage-common" which depend on guzzle 6.0. This prevent updating/installing all other php packages that depend on guzzle 7x

### Steps to reproduce the issue?
try to install this package when guzzle 7.x installed

### Have you found a mitigation/solution?
No

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)

(If you think some of the information should not be shared publicly, you can e-mail the main Microsoft contributors of the repository instead.)

**Comment by XiaoningLiu** [comment]
It's a valuable ask. We should carefully evaluate the breaking changes by Guzzle 6.x -> 7.x.

**Comment by XiaoningLiu** [comment]
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by XiaoningLiu** [comment]
https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md

**Comment by stefanedberg** [comment]
I'm also having the same problem when upgrading to Laravel 8 which requires guzzle 7.

**Comment by Synalek** [comment]
@XiaoningLiu Are there any plans on this topic?

**Comment by Sopamo** [comment]
We also need this for using azure with Laravel 8.

**Comment by Fijvect** [comment]
Hello!
I have been following this PR very closely and am wondering if we might be able to get a status update?
Thank you!

**Comment by XiaoningLiu** [comment]
The PR is trakced as part of Nov release. Before that, we need to do validation for guzzle depdency on both major 6 and 7 versions.

**Comment by domihagen** [comment]
Any update?

**Comment by TomBertie** [comment]
When is this new commit going to be updated in packagist.  I'm still unable to upgrade to Laravel 8 because it is packagist records the dependency on Guzzle v6

**Comment by Synalek** [comment]
> When is this new commit going to be updated in packagist. I'm still unable to upgrade to Laravel 8 because it is packagist records the dependency on Guzzle v6

The release is still not ready:
https://github.com/Azure/azure-storage-php/milestone/2

**Comment by domihagen** [comment]
Could u please release this Changes? This PR was trackend for November-Release. Now it´s end of January....

**Comment by spaze** [comment]
@domihagen This was released end of December, see https://github.com/Azure/azure-storage-php/releases/tag/v1.5.1-common

`composer update` should give you a new release (check with `composer outdated`), I did. You can also watch new releases to get a notification.
