### ISSUE TITLE
ConnectionStringParser::_createException incorrectly calls sprintf

### ISSUE THREAD

**Issue by dluces** [Azure/azure-storage-php#25]
`sprintf` accepts a variable number of arguments, while an array needs to be passed here instead. An alternative is to call `vsprintf` instead.

You can test this error like this:

``` php
use MicrosoftAzure\Storage\Common\Internal\StorageServiceSettings;

StorageServiceSettings::createFromConnectionString('invalid');
```

You can see a simple fix for this [here](https://github.com/Azure/azure-storage-php/compare/Azure:dev...dluces:patch-1?expand=1).

**Comment by katmsft** [comment]
Thanks for notifying. You are more than welcome to make a pull request regarding the issue.

**Comment by dluces** [comment]
Hey @katmsft, thanks for replying. Created PR #33.
