### ISSUE TITLE
Open for use of v7.X of guzzlehttp/guzzle

### ISSUE THREAD

**Issue by lalpur** [Azure/azure-storage-php#253]
better to support guzzle v7.x on storage-common-php 
because it will not work on laravel 8.

by default laravel 8 need guzzle ^v7.x

so please support latest version of guzzle.

already issue there ..https://github.com/Azure/azure-storage-common-php/issues/2

**Comment by XiaoningLiu** [comment]
Thanks for bring it up, put into next release backlog.

**Comment by andrei-dascalu** [comment]
Looking forward to this as well

**Comment by chiragpipariya** [comment]
I have the same issue in laravel 8, can we have any update in this library?

**Comment by XiaoningLiu** [comment]
Nov release will include this.

**Comment by MrThePlague** [comment]
> Nov release will include this.

Is there an approximate ETA for this release?

**Comment by WouterSioen** [comment]
Also hoping for a quick release here.

**Comment by Surt** [comment]
> Also hoping for a quick release here.

same here

**Comment by chiragpipariya** [comment]
@XiaoningLiu When library update release ?

**Comment by WouterSioen** [comment]
Nice that this got merged. Any timing for a release now?

**Comment by megacarlossm** [comment]
Please, we're waiting for this release, is there a posibility to be released this year?
