### ISSUE TITLE
Azure File Share - File gets corrupted when uploading a file larger than 4 MB

### ISSUE THREAD

**Issue by jigneshp417** [Azure/azure-storage-php#261]
### Which service(blob, file, queue, table) does this issue concern?
file (fileShare)

### Which version of the SDK was used?
"name": "microsoft/azure-storage-file",
"version": "1.2.2",

### What's the PHP/OS version?
PHP Version 7.3.21

### What problem was encountered?
If I upload file below 4 MB size its working fine. but when I upload file size more then 4 MB I got below error
Fail:
Code: 413
Value: The request body is too large and exceeds the maximum permissible limit.
details (if any): ﻿RequestBodyTooLarge
The request body is too large and exceeds the maximum permissible limit.
RequestId:978b114b-a01a-0020-77ed-9fb7f2000000
Time:2020-10-11T16:41:07.1523861Z
MaxLimit4194304

Please provide us solution with sample code how I can upload a large file in azure fileShare using. I can upload a large file with Azure blob ( Container )
Storage. it's working there. but it's not working with Azure fileShare.

### Steps to reproduce the issue?
Find the same issue with every time on upload file

### Have you found a mitigation/solution?
No we don't have found any solution.

### Is there a failing request ID related to this problem returned by server? What is it?
No

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)
This is not unique to our Azure environment. This is a limitation in the above SDK for Azure File Share.  Please let us know as soon as this is fixed. 

(If you think some of the information should not be shared publicly, you can e-mail the main Microsoft contributors of the repository instead.)

**Comment by katmsft** [comment]
Hi, Can you elaborate on which API you use? There are multiple APIs to create the file and upload the file's content. Some APIs have limitations of a 4MB file size.

**Comment by jigneshp417** [comment]
Hello,

As defined above I am using microsoft/azure-storage-file https://github.com/Azure/azure-storage-file-php **SDK**

Please check below code which **I used for upload file in fileShare**

$range_size = ($size > 0) ? $size-1:$size;

$range = new Range(0, $range_size);
$content = @fopen($file, "r");
try {
	// Create file.
	$fileClient->createFile($shareName, $fileName, $size);
	// Put ranges.
	$fileClient->putFileRange($shareName, $fileName, $content, $range);
} catch (ServiceException $e) {
	$code = $e->getCode();
	$error_message = $e->getMessage();
	$code . ": " . $error_message . PHP_EOL;
}
@fclose($content);


I used this for using your **reference sample code** from here

Reference: https://github.com/Azure/azure-storage-php/blob/master/samples/FileSamples.php

function putFileRanges($fileClient)
{
    $shareName = 'myshare' . generateRandomString();
    $fileName = 'myfile' . generateRandomString();
    $content = generateRandomString(512);
    $range = new Range(0, 511);
    try {
        // Create share.
        createShareWorker($fileClient, $shareName);
        // Create file.
        $fileClient->createFile($shareName, $fileName, 1024);
        // Put ranges.
        $fileClient->putFileRange($shareName, $fileName, $content, $range);
    } catch (ServiceException $e) {
        $code = $e->getCode();
        $error_message = $e->getMessage();
        echo $code . ": " . $error_message . PHP_EOL;
    }
}

**Comment by katmsft** [comment]
Hi,

Unfortunately `putFileRange` only supports range below 4MB on REST level, please take a look at this doc: https://docs.microsoft.com/en-us/rest/api/storageservices/put-range

You can instead use [`createFileFromContent`](https://github.com/Azure/azure-storage-file-php/blob/master/src/File/FileRestProxy.php#L2306) to create the file for content larger than 4MB.

**Comment by jigneshp417** [comment]
Hello,

Thanks for your reply. There is some question please answer it.

What's the maximum file size that it allows uploading?  

I tried uploading 91 MB, 201 MB, and 1.2 GB PDF files. Only 91 MB PDF file got uploaded and both 201 MB, and 1.2 GB PDF file upload attempts were failed. Is there any way to upload larger files?

Thanks

**Comment by jigneshp417** [comment]
Hello,

I have got below error with 201 MB file when I try to upload file.

![file-size-error](https://user-images.githubusercontent.com/72725374/97392132-08eac080-1907-11eb-8d51-808007bc685b.png)

**Comment by katmsft** [comment]
Which API were you using that failed?

**Comment by jigneshp417** [comment]
Hello,

As defined above I am using microsoft/azure-storage-file https://github.com/Azure/azure-storage-file-php SDK

I have used below code.

$content = file_get_contents($file);
try {
	// Use createFileFromContent instead of createFileFromContentAsync
	$fileClient->createFileFromContent($shareName, $fileName, $content, null);
	echo "<p style='color:green;'>File Uploaded successfully </p>";

} catch (ServiceException $e) {
	$code = $e->getCode();
	$error_message = $e->getMessage();
	$code . ": " . $error_message . PHP_EOL;
}

Thanks
