### ISSUE TITLE
BlobRestProxy::listBlobs issues with a prefix with a comma (,)

### ISSUE THREAD

**Issue by dluces** [Azure/azure-storage-php#27]
**Reproduce**
1. Create a blob called: `my dir, and that/subdir/blob.txt`
2. Try to list blobs inside the `my dir, and that` "directory"

**Sample Code**

``` php
$container_name = 'test-container';

$options = new ListBlobsOptions();
$options->setDelimiter('/');
$options->setPrefix('my dir, and that/')

try {
    // This will throw an exception for a 403 response
    $blob_list = $this->blob_proxy->listBlobs(
        $container_name,
        $options
    );
} catch (\Exception $e) {
    // ...
}
```

**Error Response**

```
Fail:
Code: 403
Value: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
details (if any): ﻿<?xml version="1.0" encoding="utf-8"?><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:bce16b9e-0001-0094-15dc-f4e755000000
Time:2016-08-12T20:59:37.6311976Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '###' is not the same as any computed signature. Server used following string to sign: 'GET




application/x-www-form-urlencoded
Fri, 12 Aug 2016 20:59:38 GMT





x-ms-version:2015-04-05
/testaccount/test-container
comp:list
delimiter:/
prefix:my dir, and that/
restype:container'.</AuthenticationErrorDetail>.
```

**Potential Issue**
From the [documentation](https://msdn.microsoft.com/en-us/library/azure/dd179428.aspx) to build the Canonicalized Resource String for _2009-09-19 and later Shared Key Format_:

> If a query parameter has more than one value, sort all values lexicographically, then include them in a comma-separated list:
> parameter-name:parameter-value-1,parameter-value-2,parameter-value-n

I believe this is not being considered by the SDK, taking into account that the prefix does not seem to be able to have multiple values. For query parameters that cannot have more than one value, I would expect the SDK to do whatever is needed for it to be interpreted as a single value, and not many values (URL encoding the comma character prevents the error from being raised but it does not return the appropriate results).

**Comment by dluces** [comment]
Anyone?

**Comment by katmsft** [comment]
After some investigation both on this SDK and other Azure SDKs including .NET and Node JS, I found that the best way of doing this is to discard this logic here and guarantee the string of any multi-value query has already been sorted. In the ServiceRestProxy there is a function called groupQueryValues that would do the job.
```
public function groupQueryValues($values)
{
    Validate::isArray($values, 'values');
    $joined = Resources::EMPTY_STRING;
    foreach ($values as $value) {
        if (!is_null($value) && !empty($value)) {
            $joined .= $value . Resources::SEPARATOR;
        }
    }
    return trim($joined, Resources::SEPARATOR)  
}
```
Once the sorting is moved here there should be one more job to do, that is replacing any code that construct a  multi-value query by calling this function.
Again there is no point of not making this function static for easier future usage since it is just another helper function.

**Comment by dluces** [comment]
Hey @katmsft, thanks for replying. Created PR #34.

**Comment by katmsft** [comment]
Suggest to close.
