### ISSUE TITLE
Thumbnails? (Feature request)

### ISSUE THREAD

**Issue by dearsina** [Azure/azure-storage-php#275]
Does there already exist a way of accessing the [thumbnail API endpoint](https://southafricanorth.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-ga/operations/56f91f2e778daf14a499f20c?
) via this SDK? If not, can one be created?

Thank you!

**Comment by katmsft** [comment]
Sorry, this SDK only supports Storage service. Please open issue in https://github.com/Azure/azure-sdk-for-php instead for other services.

**Comment by dearsina** [comment]
You're absolutely right, my apologies.
