### ISSUE TITLE
getContentStream out of memory due to not being a true stream

### ISSUE THREAD

**Issue by timhaak** [Azure/azure-storage-php#30]
getContentStream should return a true stream so allowing for large file downloads.

Currently it pulls the full file into memory before streaming out.

Which obviously causes php to run out of memory on large files.

Either it should be a true stream or rather then don't refer to it as a stream, which it isn't in the true sense, but download or something similar.

Otherwise people will get confused.

**Comment by katmsft** [comment]
Hi,
The issue should be related to the implementation of create function in GetBlobResult.php. It is currently returning the response body as a whole string but somehow converted it into a stream to align with the type $_contentStream should be. Further investigation will be made to solve the issue.

**Comment by timhaak** [comment]
Thanks :)

Currently have it working by downloading the file in pieces. 

But would be nice to have it as stream as make the process simpler.

**Comment by katmsft** [comment]
This is resolved by release 0.11.0, we also created an API for you to download files directly to a path. Check it out and feel free to leave comment!
