### ISSUE TITLE
Authorization header is missing on requests using SAS token

### ISSUE THREAD

**Issue by Pwnobbypure** [Azure/azure-storage-php#300]
### Which service(blob, file, queue, table) does this issue concern?
Queue

### Which version of the SDK was used?
microsoft/azure-storage-common: v1,5,1
microsoft/azure-storage-queue: v1.3.3

### What's the PHP/OS version?
PHP version: 7.2.34

OS: docker-compose php:7.2-apache image
`cat /etc/os-release` displays
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
and `uname -r` displays
```
5.10.25-linuxkit
```

### What problem was encountered?
Authorization header is not included on requests that use a SAS token.

### Steps to reproduce the issue?
```
$serviceQueue = '<my_queue_name>';
$connectionString = "QueueEndpoint=<https>;SharedAccessSignature=<SAS_token>";
$queueClient = \MicrosoftAzure\Storage\Queue\QueueRestProxy::createQueueService($connectionString);
$result = $queueClient->createMessage($serviceQueue, 'This is a test');
```
### Have you found a mitigation/solution?
I took a dive into the vendor code and noticed that the `signRequest()` function in `microsoft/azure-storage-common/src/Common/Internal/Authentication/SharedAccessSignatureAuthScheme.php` states in the block comment that it "Adds authentication header to the request headers"... However codewise this is not true, it is instead appending the SAS token as a query parameter which I believe is incorrect (I tested modifying the vendor code to add the SAS token in the authentication header instead and it worked as expected).
![image](https://user-images.githubusercontent.com/28726625/125233309-dd7ef900-e310-11eb-8d76-cc4c1b44bb7b.png)

### Is there a failing request ID related to this problem returned by server? What is it?
Failed response:
```
MicrosoftAzure\Storage\Common\Exceptions\ServiceException: Fail:
Code: 401
Value: Unauthorized
details (if any): <Error><Code>401</Code><Detail>MissingToken: The authorization header was not found. To know more visit https://aka.ms/sbResourceMgrE
xceptions. . TrackingId:b0cc64de-a564-4992-903f-89b101688e94_G28, SystemTracker:redacted
s, Timestamp:2021-07-12T01:36:08</Detail></Error>.


```

**Comment by XiaoningLiu** [comment]
It's by design to not have SAS in authentication header. SAS is a part of URL query parameters.

**Comment by Pwnobbypure** [comment]
> It's by design to not have SAS in authentication header. SAS is a part of URL query parameters.

May I please have an example of how to pass the SAS token as a URL query parameter?

I've tried supplying it in the connection string both, as defined in the README.md,
> BlobEndpoint=myBlobEndpoint;QueueEndpoint=myQueueEndpoint;TableEndpoint=myTableEndpoint;FileEndpoint=myFileEndpoint;SharedAccessSignature=sasToken

as well as a query parameter and both don't work...

![image](https://user-images.githubusercontent.com/28726625/129322574-09db72f7-2694-4ada-bb9e-09cde0935e4b.png)

![image](https://user-images.githubusercontent.com/28726625/129323184-fa0c0ec8-2fe2-4270-917a-1a00deaa3ef4.png)

I am generating the SAS token using the function derived from the one provided on the Microsoft documentation https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token#php

Here's my code: 
![image](https://user-images.githubusercontent.com/28726625/129325766-2624368a-06bd-43f9-9ec9-02b28cb1514e.png)

P.S: If it's by design to not have SAS in the authentication header then does that mean that the block comment for the `signRequest()` function in the `\MicrosoftAzure\Storage\Common\Internal\Authentication\SharedAccessSignatureAuthScheme` class is incorrect? Because it's pretty misleading...
![image](https://user-images.githubusercontent.com/28726625/129326816-fc3d4439-b433-4a82-b458-99d939e0bb93.png)

**Comment by katmsft** [comment]
https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview#sas-token
> 
![image](https://user-images.githubusercontent.com/21050104/132150460-eda17129-4460-42a3-8ddf-ab8e4799eca8.png)

**Comment by Pwnobbypure** [comment]
Finally got a chance to get back to this.

I think my issue may have been that I'm using a service bus endpoint when this package is intended for the storage API endpoints?

Closing this ticket.
