### ISSUE TITLE
Call upon all entity properties?

### ISSUE THREAD

**Issue by logicaloperations** [Azure/azure-storage-php#32]
Currently when creating the ticket, the only way to call upon entity properties is by using 
`$entity->getProperty("<property>")`

Replacing <property> with the property you would like to retrieve. There is no way to retrieve all properties at once. 

Suppose you could make an option for this? Because if entity 1 has the property 1 and 2 while entity 2 has the property 1 and we do a query where both entity comes up as results but we call property 1 and 2 we will encounter an error.

Is there a workaround for this?

**Comment by katmsft** [comment]
In the Entity class there is a method that user can call to get all properties at once:
`public function getProperties()`
This function will return a array that contains all the properties to the user.
