### ISSUE TITLE
E_DEPRECATED: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated for PHP 8.1

### ISSUE THREAD

**Issue by lukasestvanc** [Azure/azure-storage-php#323]
### Which service(blob, file, queue, table) does this issue concern?
BLOB

### Which version of the SDK was used?
1.5.3

### What's the PHP/OS version?
8.1.2/Windows & Linux

### What problem was encountered?
 Passing null to parameter #1 ($haystack) of type string is deprecated for PHP 8.1
{"...\\vendor\\microsoft\\azure-storage-blob\\src\\Blob\\Models\\CopyState.php","line":77}

### Steps to reproduce the issue?
$listBlobsOptions = new ListBlobsOptions();
$listBlobsOptions->setPrefix('xxxxx');
$result = $blobClient->listBlobs($containerName, $listBlobsOptions);

**Comment by spaze** [comment]
Similar issue reported in #320, both are fixed in #321.
