### ISSUE TITLE
Notice on upcoming Breaking Change.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-storage-php#48]
Dear all,

This is a short notice for upcoming breaking change that will occur in the next release. 

### Strong Type
After some internal discussion, strong type(a.k.a type hinting) will be applied to the current SDK. The general rules for the strong type is listed below:
1. For ‘int’, ’string’ and mixed type that accept multiple types, do not use strong type.
2. For ‘array’, ‘callable’ and other self-defined or user defined type, use strong type to indicate the type.

### Change of return value of some APIs
E.g. `createBlobBlock` and `createBlockBlob` returns `CopyBlobResult`, which does not seem to be correct.

There are possibly other breaking changes that will be updated once finalized.

**Comment by vinjiang** [comment]
Implemented in [0.12.0](https://github.com/Azure/azure-storage-php/releases/tag/v0.12.0).
