### ISSUE TITLE
[RFC] Adopt PSR-2 as basic coding standard

### ISSUE THREAD

**Issue by nowenL** [Azure/azure-storage-php#5]
Migrate from Azure/azure-sdk-for-php#793

This is a RFC created to propose and debate about PSR-2 as coding standard base.

**Comment by dkarlovi** [comment]
I believe it's a no brainer, by picking the most common CS you get support for all the standard tooling out of the box. Go for it.

**Comment by nowenL** [comment]
Thanks for the suggestion. I think I will just go with phpcs & phpcbf to get this done.

**Comment by katmsft** [comment]
Suggest to close as this is addressed in 0.11.0.

**Comment by vinjiang** [comment]
@dkarlovi , feel free to let us know if you have further questions.

**Comment by dkarlovi** [comment]
@vinjiang I was just commenting on a RFC. :) Maybe you should adopt [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) instead of Code Sniffer, seems to be better maintained and can also **fix** the errors instead of just reporting them.

**Comment by katmsft** [comment]
@dkarlovi When it comes to introducing another dependency to the project, we become very cautious. But thanks for the advice. Could you create a new issue so that this can be discussed with other users/contributors?

**Comment by dkarlovi** [comment]
@katmsft as you should be.

But seeing this isn't a runtime dependency but instead a development dependency, I think it's worth considering. I'll open an issue.
