### ISSUE TITLE
[Tooling] replace Code Sniffer with PHP CS Fixer for PSR2 coding style compliance

### ISSUE THREAD

**Issue by dkarlovi** [Azure/azure-storage-php#52]
As discussed in #5, consider replacing CodeSniffer with [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) which enables you to ship your CS requirements with the project (easier setup and use by all collaborators) and fix the issues for you (say, from a pre-commit hook) instead of just reporting them.

**Comment by carusogabriel** [comment]
Can I submit a PR with it?

**Comment by XiaoningLiu** [comment]
php-cs-fixer is already included in the build process
