### ISSUE TITLE
Urgent Problem with File Uploads

### ISSUE THREAD

**Issue by boredom2** [Azure/azure-storage-php#53]
Hi there,

thanks for you really great Library.
Since we updated to 0.12 (on PHP 7.1). we face a Problem with Uploading some Files, which did not occur in previous Versions (funny enough, most Files work normally, but some Files dont).

A Test Scenario is the Upload of a local .zip File (1.8MB), which always fails.
Actually, when calling createBlockBlob(...), the Call is taking some Minutes, and then an Exception is thrown, which basically is a cURL Exception:
[errno] => 56
[error] => Recv failure: Connection reset by peer

After some Tests with the SDKs Code, I was able to make the Upload work again by removing "result=false" in \Storage\Common\Internal\Utilities::isStreamLargerThanSizeOrNotSeekable the Line 782.
TBH, I am not an Expert in PHP Streams, so I dont really understand, what the $strem->read(1)=="" is checking, but disabling this Check (= keeping "result=true") is leading to the correct Behavious.

The result of this Change is, that createBlockBlobByMultipleUploadAsync is called instead of createBlockBlobBySingleUploadAsync - so maybe the real Problem is in there?

Would be great if we could solve this Issue in a better way than removing some Lines in you Code:)

Thanks,
Christoph

**Comment by katmsft** [comment]
Hi @boredom2 ,
Thanks for your effort in debugging and reporting the issue, it is really valuable for us.

`$stream->read(1)==""` is what we do after we found that there is an bug regarding the stream interface we use. If we read exactly the content length of a stream, and call `$stream->eof()`, the return value will be `false`, not the expected `true`. That is why we made this work-around.

Regarding your issue, is it possible for you to paste your php configuration file which is the `php.ini` in your php installation folder? Normally for file size lower than 32MB it is natural for the SDK to call the `createBlockBlobBySingleUploadAsync`, we do have test cases for this API so there could be something that we missed.

Also could you please confirm the last version of this SDK you used with no problems?

Best regards,
Tank

**Comment by boredom2** [comment]
Hi there and thanks for your Response.

sure, I can send you the php.ini (which wasnt really changed at all except some parts for Filesizes and Error Logic).
[php.ini.txt](https://github.com/Azure/azure-storage-php/files/721950/php.ini.txt)

Just to make sure - very often, the new SDK works - with small Files (like Images) and also big Files (like really huge Video Files). Just sometimes, it fails and tries to go on forever.

(If you are interested in that File - you can download it here:
https://nexxtvupload.blob.core.windows.net/omnia/103/11841_1484908147168.zip?st=2017-01-22T13%3A13%3A00Z&se=2017-01-27T12%3A13%3A00Z&sp=r&sv=2015-12-11&sr=b&sig=hhE7sMr9EXsGYqb%2FQA5Vrgi3fpngqh1o%2F5ULqQi%2BOb8%3D
)

And yes, I can confirm, that this Problem did not occur in Version 0.10.2 (we did not use 0.11 in Production).
In fact, on our current Production Servers, we use 0.10.2 (and this special Files works without any Problems) and we use 0.12 on our Staging Machines, where it fails.

Thanks,
Christoph

**Comment by katmsft** [comment]
I am currently trying to locate the problem, but it seems there is a huge problem here with the configuration file. In our [README.md](https://github.com/Azure/azure-storage-php/blob/master/README.md) we stated that the SDK requires our client to enable some PHP built-in extensions. However I did not find any of them enabled in the configuration file you sent me. Could you please confirm on this and if possible could you try enable them and run the code again?
The problem behind this is that our dependency uses some of the extension for some task. If the extension is not enabled it will not report any failure but some operation will just be too slow to complete. The extension are: `php_fileinfo.dll`,`php_mbstring.dll`,`php_openssl.dll`,`php_xsl.dll` and `php_curl.dll`.
In the meantime I will try to reproduce the issue on my machine with the file you provide.

**Comment by boredom2** [comment]
We are on Ubuntu 16.04, there are absolutely no .DLLs :)
But all of these Extenstions are enabled (please remember - your SDK is working fine everywhere in our really huge Setup on a couple of 100s permanently active Machines without Issues normally :P).
It is not a GENERAL Issue, it just occurs from Time to Time (and ALWAYS with the File I send here).

**Comment by hasonmsft** [comment]
@boredom2 , looks like the underlying guzzle has some problem when uploading some "big" file with stream directly. Could you update [createBlockBlobBySingleUploadAsync] (https://github.com/Azure/azure-storage-php/blob/75489c0aa0532df9b4deedf2234d588664058610/src/Blob/BlobRestProxy.php#L1621) to the code as below have a try? 

```
$body = Psr7\stream_for($content)->getContents();
```

**Comment by boredom2** [comment]
Wow :)
Well, actually, this works without any Problems.
I reworked the Change in \Storage\Common\Internal\Utilities::isStreamLargerThanSizeOrNotSeekable and changed your Line in  createBlockBlobBySingleUploadAsync - and works perfectly :)

Thats pretty awesome! Can I keep this change?

**Comment by hasonmsft** [comment]
@boredom2 , this should be the final fix. You can keep it. We'll get you updated about the release with the fix. Then you can upgrade the dependency.

**Comment by katmsft** [comment]
@boredom2 Release 0.12.1 should have the right behavior regarding this issue. The fix is temporary, in the upcoming release a more proper fix will be applied. Stay tuned. Thanks for the help in investigating the issue.

**Comment by katmsft** [comment]
@boredom2 0.13.0 has a more robust fix for the issue. Feel free to leave your comment!

**Comment by boredom2** [comment]
Looks very good so far, thanks!
We move it to Production now :)

**Comment by katmsft** [comment]
@boredom2 Glad to have your feedback, this issue will be closed.
