### ISSUE TITLE
Unable to use Storage Emulator with tables

### ISSUE THREAD

**Issue by kyleweishaupt** [Azure/azure-storage-php#58]
I'm having a fatal error with the SDK connecting to Table Storage through the Azure Storage Emulator. An OutOfRangeInput exception is thrown when trying to query/create tables specifically. All of my connection info is in lowercase format, and the same code works just fine on the live Azure storage.

Here's a sample of code that produces the problem:
```
// Works!
$this->__tableClient = ServicesBuilder::getInstance()->createTableService($this->__connectionString);
echo '<pre>', print_r($this->__tableClient->queryTables()), '</pre>';

// Fatal error :(
// I receive an instance of the table service, but any subsequent method throws exceptions.
$testClient = ServicesBuilder::getInstance()->createTableService('UseDevelopmentStorage=true;');
echo '<pre>', print_r($testClient->queryTables()), '</pre>';
```

I have also tried using a connection string specifying BlobEndpoint, TableEndpoint, and QueueEndpoint with the correct port and such, along with the well-known account and access key.

After digging through the code and exception, I can't seem to find anything more detailed than OutOfRangeInput and code 400. I even used Fiddler to check the request and couldn't get anything else.

**Comment by mirobers** [comment]
What versions of the client library and storage emulator are you using? Also, could you provide the fiddler trace of the failing request?

**Comment by kyleweishaupt** [comment]
This is on Azure Storage Emulator version 4.6.0.0, and client library release 0.12.1.

Here's a raw request in fiddler:
```
GET /Tables HTTP/1.1
Host: 127.0.0.1:10002
Connection: Keep-Alive
content-type: application/x-www-form-urlencoded
x-ms-version: 2015-04-05
dataserviceversion: 1.0;NetFx
maxdataserviceversion: 2.0;NetFx
accept: application/atom+xml,application/xml
accept-charset: utf-8
User-Agent: Azure-Storage/0.10.0 (PHP 7.0.14)
date: Thu, 02 Feb 2017 15:32:37 GMT
authorization: SharedKeyLite devstoreaccount1:adHQdZnVGOUcVMK/G1o8TGwNSXn4XDzHjwFYgy2oGlw=
```
 
And here's the response: 
```
HTTP/1.1 400 One of the request inputs is out of range.
Content-Length: 325
Content-Type: application/xml
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 2fa2f00d-8507-4eef-9012-1f7783679282
Date: Thu, 02 Feb 2017 15:32:36 GMT
```

**Comment by katmsft** [comment]
You are using client library release 0.12.1 but the request has a wrong version number of 0.10.0, it is very strange. Needs further digging on the issue.
`User-Agent: Azure-Storage/0.10.0 (PHP 7.0.14)`

**Comment by kyleweishaupt** [comment]
@katmsft Yes, I noticed that as well. I first noticed this issue when trying to set up local development storage using flysytem, in which the Azure adapter requires version ~0.10.1.

For this issue & Fiddler request I created a new project using the the 0.12.1 release and without any other dependencies. Not sure why the User Agent is still showing 0.10.0 though.

**Comment by katmsft** [comment]
After some digging I found that the SDK uses a method called `withPath` [here](https://github.com/Azure/azure-storage-php/blob/master/src/Common/Internal/ServiceRestProxy.php#L280) for the operation of adding path to the basic uri. It will however replace the previous path, which in this case is the account name of the service, causing the operation to fail.
If you just change L279 to L281 to the code below the SDK will function properly. The fix will be applied in the next release.
```
if ($path != null) {
    $exPath = $uri->getPath();
    if ($exPath != '') {
        if ($path[0] == '/') {
            $path = $exPath . substr($path, 1);
        } else {
            $path = $exPath . $path;
        }
    }
    $uri = $uri->withPath($path);
}
```

**Comment by katmsft** [comment]
@kyleweishaupt @mirobers

**Comment by kyleweishaupt** [comment]
@katmsft Thank you for the workaround!! I'll be anxiously waiting for the next release 👍

**Comment by katmsft** [comment]
@kyleweishaupt 0.13.0 now has the fix for this issue.
