### ISSUE TITLE
Create an asset from a existing blob

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-storage-php#59]
Copy from https://github.com/Azure/azure-sdk-for-php/issues/915:

@cassianotartari

Hi!
I'm trying to figure out how to create an asset to streaming using an already uploaded video to blob storage. The storage is the same used in media services.
I've tried to use Iblob::copyBlob but it seems to not accept the asset as destination.
Now I'm thinking in use Iblob::getBlob to get file content and MediaServicesRestProxy::uploadAssetFile to set this content to my assetFile.
Is this the way?
Thanks.

**Comment by katmsft** [comment]
@cassianotartari 
Hi,

`copyBlob` is used to copy blobs within the Azure Storage account. And from what I understand the what you mentioned asset to streaming cannot use this API. What you said is correct: use `Iblob::getBlob` then use `GetBlobResult::getContentStream` will give you a stream(resource) that can be passed to `MediaServicesRestProxy::uploadAssetFile`. However this download first and then upload the file.

@sergey-shandar could you clarify what this `locator` is in `public function uploadAssetFile(Locator $locator, $name, $file)` and if it is using the Azure storage service and how could one get the exact path containing the name of the container and the name of the blob if it is?

**Comment by cassianotartari** [comment]
Thanks @sergey-shandar and @katmsft but download to VM and upload again to storage just to create the asset doesn't seem to be efficient. I'm talking here about video files with high resolution that could have an hour of duration.

Isn't other way to convert a blob to asset?

**Comment by katmsft** [comment]
@cassianotartari Thanks for clarifying. I am from Azure Storage team so what I could do is to help you understand the behavior of Blobs, and I will try my best help you get what you need if possible.

@sergey-shandar could you clarify what the underlying Media Service uses to store the asset and if there is any rest API that can directly transform an existing blob to an asset? And what is the difference between a media asset to a blob or file in the storage account?

**Comment by cassianotartari** [comment]
The closest that I get is:
```php
$asset = new Asset(Asset::OPTIONS_NONE);
$asset->setName('Mezzanine_'.$midia->getNome());
$asset = $this->mediaServicesRestProxy->createAsset($asset);

$access = new AccessPolicy('[Some access policy name]');
$access->setDurationInMinutes(440);
$access->setPermissions(AccessPolicy::PERMISSIONS_WRITE);
$access = $this->mediaServicesRestProxy->createAccessPolicy($access);

$sasLocator = new Locator($asset, $access, Locator::TYPE_SAS);
$sasLocator->setStartTime(new \DateTime('now -5 minutes'));
$sasLocator = $this->mediaServicesRestProxy->createLocator($sasLocator);

$asset = $this->mediaServicesRestProxy->getAsset($asset->getId());

$this->blobProxy->copyBlob($asset->getUri(), $midia->getNome(), 'mycontainer', $midia->getMidiaPath(true));
$this->mediaServicesRestProxy->createFileInfos($asset);
```

Where:

- ``$midia->getNome()`` returns a filename
- ``$midia->getMidiaPath(true)`` returns the filepath with filename
- ``$this->mediaServicesRestProxy`` is ``WindowsAzure\MediaServices\MediaServicesRestProxy``
-  ``$this->blobProxy`` is ``MicrosoftAzure\Storage\Blob\BlobRestProxy``

But it is throwing:
```
Fail:
Code: 400
Value: The specifed resource name contains invalid characters.
details (if any): ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:fb2033fa-0001-003e-68f2-86fed1000000
Time:2017-02-14T18:45:48.7420066Z</Message></Error>.
```
![screenshot from 2017-02-14 16-46-25](https://cloud.githubusercontent.com/assets/3017642/22943595/38e9681a-f2d5-11e6-84ef-1cdc2fa89a59.png)

**Comment by sergey-shandar** [comment]
AFIAK, this question is about the Media Service itself, not about SDK. I think @johndeu may help with this.

**Comment by johndeu** [comment]
Sergey is correct, this is not a Storage SDK issue. It's more about integration with storage and media services. 

See this article on copying asset from an existing blob:
https://docs.microsoft.com/en-us/azure/media-services/media-services-copying-existing-blob

Let me know if you have further questions.

**Comment by cassianotartari** [comment]
> AFIAK,  this question is about the Media Service itself, not about SDK. I think @johndeu may help with this.
That' why I've opened [here](https://github.com/Azure/azure-sdk-for-php/issues/915).

> See this article on copying asset from an existing blob:
> https://docs.microsoft.com/en-us/azure/media-services/media-services-copying-existing-blob
@johndeu I've already read this a couple of times but the closest I got in PHP was the code above. Can you help me?

**Comment by cassianotartari** [comment]
ping @jcookems @sergey-shandar and others...

**Comment by vinjiang** [comment]
We will close this issue. Feel free to let us know if you need further assistance on this SDK. You can also open issues to media service for relevant questions.
