### ISSUE TITLE
miss a "/" in <rule ref="Zend.Files.ClosingTag.NotAllowed">

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-storage-php#69]
location:azure-storage-php/build/phpcs.xml

some IDE shows error:The end-tag for element type "rule" must end with a '>' delimiter.

because you miss a "/" <rule ref="Zend.Files.ClosingTag.NotAllowed">

i think you can add "/" like <rule ref="Zend.Files.ClosingTag.NotAllowed/">

**Comment by katmsft** [comment]
Noted, will be fixed soon. Thanks for reporting.
