### ISSUE TITLE
Cannot upload images to Azure Storage (SSL error 60)

### ISSUE THREAD

**Issue by Karadaliev** [Azure/azure-storage-php#70]
As of last week the Azure's storage uploader stopped working, the error message that I'm having is:

Server error. cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

My script its hosted on Azure web app as well, here are the basic details for it:
PHP: 7.0
Platform: 64 bit

I have two web apps running with exact same script and looks like both of them stopped working about the same time the library was updated - when I pushed my changes and the composer updated all of the libraries.

**Comment by katmsft** [comment]
Hi @Karadaliev , sorry for the inconvenience but there is a following added paragraph in the README.md. Please take the mentioned action and give further updates if not working. Thanks!

## Troubleshooting
### Error: Unable to get local issuer certificate
cURL can't verify the validity of Microsoft certificate when trying to issue a request call to Azure Storage Services. You must configure cURL to use a certificate when issuing https requests by the following steps:

1. Download the cacert.pem file from [cURL site](http://curl.haxx.se/docs/caextract.html).
2. Open your php.ini file and add the following line:

    ```
    curl.cainfo = "<absolute path to cacert.pem>"
    ```

**Comment by Karadaliev** [comment]
Hay man, thank you for the answer – you and the Azure support team helped me out and I managed to solve this issue. Your solution its alright, but its not that simple in Azure web apps. Just for your information here is full solution for Azure Web Apps:

1. Open the web app in portal.azure.com
2. Go to Application Settings and add this value in the App settings section: PHP_INI_SCAN_DIR = d:\home\site\ini
3. Open web app's scm panel, for example - https://osi-bout-test.scm.azurewebsites.net/
4. Go to Debug Console > CMD
5. Open the "site" folder
6. Upload the "cacert.pem" file (download it from here: http://curl.haxx.se/docs/caextract.html)
7. Create/open the "ini" folder
8. Create/open file with the name "settings.ini"
9. Put this line inside the file: curl.cainfo = "D:\home\site\cacert.pem"
11. Go back to the app in the portal.azure.com and STOP and then START.

**Comment by katmsft** [comment]
Wow, thanks for the detailed instruction @Karadaliev . I will try it and put it somewhere so people with same issue can find the solution more easily. Again thanks for letting us know!

**Comment by olkunmustafa** [comment]
Thanks @Karadaliev it works!
