### ISSUE TITLE
IMicrosoftAzure\Storage\Common\Internal::isString() allows null (which is not a string)

### ISSUE THREAD

**Issue by dkarlovi** [Azure/azure-storage-php#79]
You can call `BlobRestProxy::listBlobs(null)` which gives:

    Undefined index: Blobs
    /microsoft/azure-storage/src/Blob/Models/ListBlobsResult.php:100

which should be fixed, but the root cause is `IMicrosoftAzure\Storage\Common\Internal::isString()` which allows for `null` because [it just tries to cast to `(string)`](https://github.com/Azure/azure-storage-php/blob/master/src/Common/Internal/Validate.php#L73) instead of using [`is_string()`](http://php.net/manual/en/function.is-string.php) (?).

**Comment by katmsft** [comment]
Thanks for the notice. It seems that the function should not have been called `isString`, better `canConvertToString` because the requirement for this function is actually to see if the parameter can be converted to a string. This will be fixed in the next update. (Possibly 0.16.0)

**Comment by katmsft** [comment]
Sorry about the delay, the fix is introduced and will be released in the 0.17.0 version.

**Comment by dkarlovi** [comment]
Thanks @katmsft!

**Comment by katmsft** [comment]
PR merged, suggest to close the issue.

**Comment by dkarlovi** [comment]
Will try it as soon as I upgrade to latest beta, thanks @katmsft.

**Comment by katmsft** [comment]
@dkarlovi Sorry to inform you that currently the version `1.0.0-beta.1` will be recalled, and will be changed to version 0.17.0. The product code will not change but the `user-agent` string and tag will be changed.

**Comment by dkarlovi** [comment]
It's not a problem for me, my project is still months away from needing to lock down deps. Thanks for the heads-up, though @katmsft.
