### ISSUE TITLE
Doesn't Support SAS Authentication

### ISSUE THREAD

**Issue by nowenL** [Azure/azure-storage-php#8]
Migrate from Azure/azure-sdk-for-php#733

This makes this library nearly unusable from a perspective of integration scenarios where you are trying to work across vendors or companies. Given that this is a potentially major use case for queues, this is glaring. We got burned, had to redo our work and went to just plain curl / php guzzle. Would have been good to at least now this up front.

**Comment by dluces** [comment]
Has anyone worked on this? I've actually had to extend the SDK to support SAS authentication so if nobody's working on this, I might be able to put my changes in a PR.

**Comment by katmsft** [comment]
Thanks for the effort, we are currently reviewing it.

**Comment by dluces** [comment]
This has been merged and released. This needs closing.

**Comment by katmsft** [comment]
@dluces Thanks for the reminder. Will close it soon.
