### ISSUE TITLE
Common\Internal\Utilities::isDouble throws a warning on PHP 7.1

### ISSUE THREAD

**Issue by spaze** [Azure/azure-storage-php#86]
A `'string' + 0` expression is forbidden and throws a `Warning: A non-numeric value encountered` warning on PHP 7.1, see [3v4l example](https://3v4l.org/vnQj5), from PHP 7.1.0 [changelog](https://secure.php.net/ChangeLog-7.php#7.1.0):

*Number operators taking numeric strings now emit E_NOTICEs or E_WARNINGs when given malformed numeric strings.*

Such construct when used in [`Common\Internal\Utilities::isDouble()`](https://github.com/Azure/azure-storage-php/blob/00b537e21bad57cbf5c8bfb69d62faa84036e6fc/src/Common/Internal/Utilities.php#L851) also throws the same warning.

It shouldn't throw a warning.

**Comment by katmsft** [comment]
Thanks for letting us know. Can I ask if `+0` is still needed in checking `is_double`? It seems that it does not do anything if `$value` is already determined as numeric.

**Comment by spaze** [comment]
The function description says *Gets if the value is a double value **or string representation** of a double* so I guess it might still be needed, though I can't say for sure, sorry, don't know the specific use cases of `isDouble()`.

Tried to draft a PR in #87, though.

**Comment by spaze** [comment]
It depends on whethere there's a string used as `$value`, if yes, then `+0` is still needed I guess.
```
var_dump(is_double('1.2'));  // false
var_dump(is_double(1.2));  // true
```
https://3v4l.org/aOCA7

**Comment by katmsft** [comment]
It does not generate any warning prior to PHP 7.1 version, maybe that's why we miss this issue in the first place. The solution seems to be legit and I will review the PR soon. Thanks for contributing.

**Comment by katmsft** [comment]
PR merged, suggest to close the issue.
