### ISSUE TITLE
Warnings when parsing non-XML strings in XmlSerializer

### ISSUE THREAD

**Issue by spaze** [Azure/azure-storage-php#88]
When parsing non-XML strings in `XmlSerializer` a warning is being returned.

Example warning:

```
Message: SimpleXMLElement::__construct(): {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The
```
The warning is generated in `ServiceException::parseErrorMessage()` because that's possibly parsing a non-XML string (as the comment *try to parse using xml serializer, if failed, return the whole body* suggests)

### Sample backtrace:
File: /media/snafu-htdocs/report-uri/report-uri/application/libraries/Microsoft/vendor/microsoft/azure-storage/src/Common/Internal/Serialization/XmlSerializer.php
Line: 241
Function: __construct

File: /media/snafu-htdocs/report-uri/report-uri/application/libraries/Microsoft/vendor/microsoft/azure-storage/src/Common/Exceptions/ServiceException.php
Line: 89
Function: unserialize

File: /media/snafu-htdocs/report-uri/report-uri/application/libraries/Microsoft/vendor/microsoft/azure-storage/src/Common/Exceptions/ServiceException.php
Line: 70
Function: parseErrorMessage

Non XML strings should not generate a warning and I have a PR incoming where the warning is silenced by calling `libxml_use_internal_errors(true)`.

Thanks for looking into this.

**Comment by katmsft** [comment]
This is an interesting issue. During development I never found any test cases that generates this warning. I will need some time dig into this issue. Thanks for reporting.

**Comment by katmsft** [comment]
PR merged. Suggest to close the issue.

**Comment by katmsft** [comment]
@spaze Sorry to inform you that currently the version `1.0.0-beta.1` will be recalled, and will be changed to version 0.17.0. The product code will not change but the `user-agent` string and tag will be changed.

**Comment by spaze** [comment]
@katmsft Thanks for the info, and also for checking my issues.
