### ISSUE TITLE
listBlobsOptions has been removed ?

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-storage-php#90]
I am trying to get blob with a specific prefix. But i am not able to execute the function. here is the code$blobListOptions = new ListBlobsOptions(); $blobListOptions->setPrefix('test/'); $blob_list = $blobRestProxy->listBlobs($container_name,$blobListOptions);

From https://github.com/Azure/azure-sdk-for-php/issues/930

**Comment by katmsft** [comment]
Suggest to close since not feed back from customer for a long time.
