### ISSUE TITLE
Failure to upload in v0.17.0

### ISSUE THREAD

**Issue by ytnobody** [Azure/azure-storage-php#95]
Environment: Azure Web Apps
PHP Version: 7.0 (Provided by Azure Web Apps)

I encountered following error when uploading a image with microsoft/azure-storage@v0.17.0

```
<b>Fatal error</b>:  Uncaught Error: Call to undefined method MicrosoftAzure\Storage\Common\Internal\Validate::isString() in D:\home\site\wwwroot\vendor\microsoft\azure-storage\src\Blob\BlobRestProxy.php:1657
Stack trace:
#0 D:\home\site\wwwroot\vendor\microsoft\azure-storage\src\Blob\BlobRestProxy.php(1519): MicrosoftAzure\Storage\Blob\BlobRestProxy-&gt;createBlockBlobBySingleUploadAsync('image-upload', 'profile__e116da...', Object(GuzzleHttp\Psr7\Stream), NULL)
#1 D:\home\site\wwwroot\vendor\microsoft\azure-storage\src\Blob\BlobRestProxy.php(1477): MicrosoftAzure\Storage\Blob\BlobRestProxy-&gt;createBlockBlobAsync('image-upload', 'profile__e116da...', '\x89PNG\r\n\x1A\n\x00\x00\x00\rIHD...', NULL)
#2 D:\home\site\wwwroot\lib\myapp.php(130): MicrosoftAzure\Storage\Blob\BlobRestProxy-&gt;createBlockBlob('image-upload', 'profile__e116da...', '\x89PNG\r\n\x1A\n\x00\x00\x00\rIHD...')
#3 D:\home\site\wwwroot\uploadImage.php(41): MyApp\App-&gt;upload_to_blob('image-upload', 'profile__e116da...', '\x89PNG\r\n\x1A\n\x00\x00\x00\rIHD...')
#4 in <b>D:\home\site\wwwroot\vendor\microsoft\azure-storage\src\Blob\BlobRestProxy.php</b> on line <b>1657</b><br />
```

As temporary solution, I locked the version of microsoft/azure-storage as v0.16.0 in composer.json. Result, the problem was solved.

Why failure in v0.17.0 ?

**Comment by katmsft** [comment]
Hmm... It is strange. Have you used `Validate::isString` in your repo? Because in 0.17.0, it is renamed to `Validate::canCastAsString`.
All the reference to this method should have changed. Could you please check if you have partially updated the SDK? Can you upload the mentioned `vendor\microsoft\azure-storage\src\Blob\BlobRestProxy.php` so I could check it for you?

**Comment by ytnobody** [comment]
I feel it's strange too. 😟 

I checked `Validate::isString` in my repo. But it isn't exists.


![ytnobody 2017-08-07 17 34 20](https://user-images.githubusercontent.com/278841/29018594-b22906c8-7b96-11e7-981c-8594372da7a0.PNG)

> Can you upload the mentioned vendor\microsoft\azure-storage\src\Blob\BlobRestProxy.php so I could check it for you?
uploaded to gist.
https://gist.github.com/ytnobody/a31386ceb93c700a4ca6a6961f8a0910

Best regards.

**Comment by katmsft** [comment]
Hi @ytnobody , it seems that you are referencing a `BlobRestProxy.php` that is not updated to 0.17.0. You can see that in the file you uploaded, line 1657 references to `public function createPageBlobFromContentAsync` while it references to `Validate::isString($container, 'container');`  in 0.16.0's code.
Could you please re-install your dependency and see if the problem has been resolved? Thanks!

Best regards.

**Comment by ytnobody** [comment]
Today I retried updating to v0.17.0 on Azure Web Apps.
Afterwards, I never seen this problem since updated. 
So I close this issue.

Maybe, I think that failure of dependency resolution evoked this problem.

Thank you.
